# Format C/C++ code via clang-format

name: Linter

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  CMAKE_VERSION: 3.15.7
  NINJA_VERSION: 1.9.0
  BUILD_TYPE: Debug
  CCACHE_VERSION: 3.7.7

jobs:
  build:
    name: Check with clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Install linux dependencies
        run: |
          sudo apt-get update -y
          ${{ github.workspace }}/desktop/linux-client-setup.sh
      - name: cmake build
        run: cmake -DBUILD_SERVER=OFF -DBUILD_CLIENT=OFF -DBUILD_TESTS=OFF .
      - name: clang-format
        run: |
          make clang-format
          git diff-index --quiet HEAD --

