# Format C/C++ code via clang-format

name: clang-format

on: [ push ]

env:
  CMAKE_VERSION: 3.15.7
  NINJA_VERSION: 1.9.0
  BUILD_TYPE: Debug
  CCACHE_VERSION: 3.7.7

jobs:
  build:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: install linux dependencies
        run: |
          sudo apt-get update -y
          ${{ github.workspace }}/desktop/linux-client-setup.sh
      - name: cmake build
        run: cmake -DBUILD_SERVER=OFF -DBUILD_CLIENT=OFF -DBUILD_TESTS=OFF .
      - name: clang-format
        run: make clang-format
      - name: Commit files
        run: |
          git config --local user.email "linter@fractalcomputers.com"
          git config --local user.name "Fractal Linter"
          git diff-index --quiet HEAD || (echo "To pass this check please lint the code" && false)
