name: 'Delete old artifacts'
on:
  push
#  schedule:
#    - cron: '0 1 * * *' # every day

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 3days # Setting this to 0 will delete all artifacts