name: Auto release PRs wait for status updates

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait_for_checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'sleep'
        run: sleep 25
      - name: 'Wait for commit status updates'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        with:
          ignoreActions: automerge
          checkInterval: 60
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"