name: Auto release PRs

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: trigger_pr_release
        # Do not run if PR title contains "WIP"
        if: "!contains(github.event.pull_request.title, 'WIP')"
        # TODO switch this to GITHUB_TOKEN once workflow_dispatch supports GHA initiated dispatches
        # (currently it requires the dispatcher to be a user, so a personal access token must be used
        # here)

        # The workflow ID can be determined by running:
        # ```
        # curl -u "$TOKEN:" \
        #   -H "Accept: application/vnd.github.v3+json" \
        #   https://api.github.com/repos/fractalcomputers/protocol/actions/workflows
        # ```

        # NOTE: the root "ref" tag points to `master` because that is the version of the workflow that
        # we want to run (as in, that is the branch containing the specific YAML file that should be used)

        # TODO enable testing once it is working reliably

        # Pipe secrets.PROC_BRANCH_BUILD_RELEASE_ID to base64 so that the user can see it in the logs
        # since GHA auto redacts secrets.
        run: |
          curl \
            -u "${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}:" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/fractalcomputers/protocol/actions/workflows/proc-branch_build_release/dispatches \
            -d '{"ref": "${{ github.ref }}", "inputs": {"ref": "${{ github.ref }}", "should_test": "false"}}'

