name: Auto release primary branches (dev, staging, master)

on:
  push:
    branches:
      - dev
      - staging
      - master

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      # TODO switch this to GITHUB_TOKEN once workflow_dispatch supports GHA initiated dispatches
      # (currently it requires the dispatcher to be a user, so a personal access token must be used
      # here)

      # The workflow ID can be determined by running:
      # ```
      # curl -u "$TOKEN:" \
      #   -H "Accept: application/vnd.github.v3+json" \
      #   https://api.github.com/repos/fractalcomputers/protocol/actions/workflows
      # ```

      # TODO enable testing once it is working reliably
      - run: |
          curl -u "${{ secrets.CI_PAT }}:" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/fractalcomputers/protocol/actions/workflows/1851975/dispatches \
            -d '{"ref": "${{ github.ref }}", "inputs": {"ref": "${{ github.ref }}", "should_test": "false"}}'