name: Sentry Release

on:
    release:
        types: [published]

jobs:
    createSentryRelease:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Set git short sha
              id: vars
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install Python requests (for sentry download)
              uses: actions/setup-python@v2
            - name: install python requests
              run: pip3 install requests
            - name: Set Sentry Environment
              id: sentry_env
              run: python3 sentry_env_from_release.py ${{ github.event.release.tag_name }}
            - name: Create a Sentry.io release
              uses: tclindner/sentry-releases-action@v1.2.0
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: Fractal
                  SENTRY_PROJECT: protocol
              with:
                  tagName: ${{ steps.vars.outputs.sha_short }}
                  releaseNamePrefix: fractal-protocol@
                  environment: ${{ steps.sentry_env.outputs.sentry_env }}
