rules:
  - name: add-customer-id-claim
    script: ./rules/add-customer-id-claim.js
    stage: login_success
    enabled: true
    order: 2
  - name: create-customer
    script: ./rules/create-customer.js
    stage: login_success
    enabled: true
    order: 1
  - name: add-subscription-status-claim
    script: ./rules/add-subscription-status-claim.js
    stage: login_success
    enabled: true
    order: 3
rulesConfigs: []
hooks: []
pages:
  - name: guardian_multifactor
    enabled: false
    html: ./pages/guardian_multifactor.html
  - name: login
    enabled: true
    html: ./pages/login.html
resourceServers:
  - name: Fractal API
    identifier: "##FRACTAL_AUTHENTICATION_API##"
    allow_offline_access: true
    enforce_policies: true
    scopes:
      - value: admin
        description: Administrative resources
      - value: backend
        description: Granted to trusted backends
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: Fractal
    allowed_clients: []
    app_type: native
    callbacks: @@FRACTAL_ELECTRON_APP_CALLBACK@@
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: The Fractal desktop application.
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://fractal-brand-assets.s3.amazonaws.com/png/icon+logo/icon_color2.png
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: none
  - name: GitHub Actions
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: A service that performs administrative operations on the fractal
      webservers on behalf of Fractal developers.
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://github.githubassets.com/images/modules/logos_page/Octocat.png
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Postman
    allowed_clients: []
    app_type: native
    callbacks:
      - https://oauth.pstmn.io/v1/callback
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: A tool that developers use to test Fractal's APIs.
    grant_types:
      - authorization_code
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://www.postman.com/assets/logos/postman-logo-stacked.svg
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: none
  - name: Webserver
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases: []
connections:
  - name: apple
    strategy: apple
    enabled_clients: []
    is_domain_connection: false
    options:
      kid: D3T9SSLTY5
      name: true
      email: true
      scope: name email
      team_id: 757Z8TDNJL
      client_id: com.fractalcomputers.fractalauth
      app_secret: "##APPLE_OAUTH_SECRET##"
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Fractal
      - Postman
    is_domain_connection: false
    options:
      email: true
      gmail: false
      orkut: false
      scope:
        - email
        - profile
      sites: false
      tasks: false
      blogger: false
      profile: true
      youtube: false
      calendar: false
      contacts: false
      analytics: false
      client_id: 581514545734-4r65pae9m63dci2rq6isstvaapuqp85l.apps.googleusercontent.com
      moderator: false
      coordinate: false
      picasa_web: false
      google_plus: false
      google_books: false
      google_drive: false
      spreadsheets: false
      client_secret: "##GOOGLE_OAUTH_SECRET##"
      document_list: false
      latitude_best: false
      latitude_city: false
      url_shortener: false
      webmaster_tools: false
      chrome_web_store: false
      allowed_audiences: ""
      adsense_management: false
      google_drive_files: false
      coordinate_readonly: false
      google_cloud_storage: false
      content_api_for_shopping: false
      google_affiliate_network: false
tenant:
  default_audience: ""
  default_directory: ""
  enabled_locales:
    - en
  flags:
    new_universal_login_experience_enabled: true
    universal_login: true
    dashboard_ui_next: true
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: ""
  picture_url: https://fractal-brand-assets.s3.amazonaws.com/png/icon+logo/icon_color2.png
  support_email: support@fractal.co
  support_url: ""
  universal_login:
    colors:
      page_background: "#ffffff"
      primary: "#4f35de"
emailProvider:
  name: sendgrid
  credentials:
    api_key: "##SENDGRID_API_KEY##"
  default_from_address: Fractal <support@fractal.co>
  enabled: true
emailTemplates:
  - template: welcome_email
    body: ./emailTemplates/welcome_email.html
    enabled: true
    from: Fractal <noreply@fractal.co>
    subject: Welcome to Fractal!
    syntax: liquid
clientGrants:
  - client_id: Webserver
    audience: "##FRACTAL_AUTHENTICATION_API##"
    scope:
      - backend
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: true
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles:
  - name: Developer
    description: A Fractal developer
    permissions:
      - permission_name: admin
        resource_server_identifier: "##FRACTAL_AUTHENTICATION_API##"
branding:
  colors:
    page_background: "#ffffff"
    primary: "#4f35de"
  logo_url: https://fractal-brand-assets.s3.amazonaws.com/png/icon+logo/icon_color2.png
prompts:
  universal_login_experience: new
  identifier_first: true
migrations: {}
actions: []
triggers: {}
organizations: []
