codecov:
  branch: dev
  require_ci_to_pass: no # Whether Codecov waits for all other statuses to pass before sending its status

# Setting coverage targets per flag
coverage:
  status:
    patch: off # Disable codecov/patch status, it's not informative
    project:
      default:
        target: auto # Overall monorepo code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
      backend-services:
        target: auto # /backend/services code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - backend-services
      extension-native-host:
        target: auto # /mandelboxes/browsers/base-chromium/extension-native-host code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - extension-native-host
      protocol:
        target: auto # /protocol code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - protocol
      socketio-server:
        target: auto # /mandelboxes/browsers/base-chromium/socketio-server code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - socketio-server
      teleport-extension:
        target: auto # /mandelboxes/browsers/base-chromium/teleport-extension code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - teleport-extension
  precision: 2 # Number of decimal places on code coverage, between 0 and 5
  round: down # Up, down, or nearest
  range: "50...90" # First number represents red, and second represents green (default is 70..100)

# Heroku CI makes /app the root on the Heroku CI instances,
# so we need this fix to retrieve /services as the root folder
fixes:
  - "**/whist/backend/services/::services/" # Make backend/services coverage relative to backend/services directory
  - "**/whist/protocol/::protocol/" # Make protocol coverage relative to protocol directory

# Settings for Codecov comments on pull requests
comment:
  layout: "diff, flags, files, footer"
  behavior: default
  require_changes: no # Whether coverage must have changed to post
  require_base: no # Whether it must have a base report to post
  require_head: no # Whether it must have a head report to post
  branches: null
  show_carryforward_flags: true

# This is where we define every flag for the Codecov uploader and update when new Flags are added
# See here for carryforward documentation: https://docs.codecov.com/docs/carryforward-flags
flags:
  backend-services:
    paths:
      - backend/services/
    carryforward: true
  extension-native-host:
    paths:
      - mandelboxes/browsers/base-chromium/extension-native-host/
    carryforward: true
  protocol:
    paths:
      - protocol/
    carryforward: true
  socketio-server:
    paths:
      - mandelboxes/browsers/base-chromium/socketio-server/
    carryforward: true
  teleport-extension:
    paths:
      - mandelboxes/browsers/base-chromium/teleport-extension/
    carryforward: true
