codecov:
    branch: dev
    require_ci_to_pass: no

coverage:
    status:
        project:
            default:
                target: auto
                threshold: 1%
    precision: 5 # Number of decimal places, between 0 and 5
    round: down # up, down, or nearest
    range: "70...90" # First number represents red, and second represents green (default is 70..100)

fixes:
    - "::webserver/"

ignore:
    - "webserver/app/sentry.py"
    - "app/sentry.py"

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

comment:
    layout: "reach, diff, flags, files, footer"
    behavior: default
    require_changes: no
