codecov:
  branch: dev
  require_ci_to_pass: no # Whether Codecov waits for all other statuses to pass before sending its status

# Setting coverage targets per flag
coverage:
  status:
    patch: off # Disable codecov/patch status, it's not informative
    project:
      default:
        target: auto # Overall monorepo code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
      webserver:
        target: auto # /webserver code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - webserver
      host-service:
        target: auto # /host-service code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - host-service
      protocol:
        target: auto # /protocol code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - protocol
      core-ts:
        target: auto # /core-ts code coverage
        threshold: 1% # Percentage of tolerable code coverage decrease from the base branch
        flags:
          - core-ts
  precision: 2 # Number of decimal places on code coverage, between 0 and 5
  round: down # Up, down, or nearest
  range: "70...90" # First number represents red, and second represents green (default is 70..100)

# Files ignored by Codecov
ignore:
  - "webserver/app/cli.py"
  - "webserver/app/config.py"
  - "webserver/app/sentry.py"

# Heroku CI makes /app the root on the Heroku CI instances,
# so we need this fix to retrive /webserver as the root folder
fixes:
  - "app/::webserver/" # Move path  e.g., "before/path" => "after/path"

# Settings for Codecov comments on pull requests
comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no # Whether coverage must have changed to post
  require_base: no # Whether it must have a base report to post
  require_head: no # Whether it must have a head report to post
  branches: null
  show_carryforward_flags: true

# This is where we define every flag for the Codecov uploader and update when new Flags are added
# See here for carryforward documentation: https://docs.codecov.com/docs/carryforward-flags
flags:
  webserver:
    paths:
      - webserver/
    carryforward: true
  host-service:
    paths:
      - host-service/
    carryforward: true
  protocol:
    paths:
      - protocol/
    carryforward: true
  core-ts:
    paths:
      - core-ts/
    carryforward: true
