# dependabot.yml
#
# Configuration file for Dependabot on the fractal/fractal monorepository.

# Note: Dependabot does not support globbing as of the writing of this file. As
# a result, this configuration file is structured on a per-subrepo basis and
# dependency package manager files must be provided explicitly.

version: 2

updates:
    ################### GitHub Actions ##################

    - package-ecosystem: "github-actions"
      directory: "/" # default location of `.github/workflows`
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/.github/workflows/helpers" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/.github/workflows/helpers/notifications" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/.github/workflows/helpers/aws" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/config/build" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/config" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/.github/actions/set-environment" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ################ Client-Applications ################

    - package-ecosystem: "npm"
      directory: "/client-applications/desktop" # looks for package.json and [package-lock/yarn].lock file in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ################## Container-Images #################

    - package-ecosystem: "docker"
      directory: "/container-images/base" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/container-images/browsers/chrome" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/container-images/browsers/firefox" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/container-images/helper_scripts" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/container-images/testing_scripts" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ###################### Core-ts ######################

    - package-ecosystem: "npm"
      directory: "/core-ts" # looks for package.json and [package-lock/yarn].lock file in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ################## ECS-Host-Service #################

    - package-ecosystem: "gomod"
      directory: "/ecs-host-service" # looks for go.mod and go.sum in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ################### Main-Webserver ##################

    - package-ecosystem: "pip"
      directory: "/main-webserver/db_migration" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/main-webserver/scripts" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/main-webserver/analytics" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/main-webserver/docker" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    - package-ecosystem: "pip"
      directory: "/main-webserver" # looks for requirements.txt in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ################### Microservices ###################

    - package-ecosystem: "npm"
      directory: "/microservices/auth0" # looks for package.json and [package-lock/yarn].lock file in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ###################### Protocol #####################

    - package-ecosystem: "docker"
      directory: "/protocol" # looks for Dockerfile in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
    ###################### Website ######################

    - package-ecosystem: "npm"
      directory: "/website" # looks for package.json and [package-lock/yarn].lock file in this directory
      schedule:
          interval: "monthly" # runs on the first day of each month
      ignore:
          - dependency-name: "*" # ignore all micro/patch updates for all dependencies
            update-types: ["version-update:semver-patch"]
      open-pull-requests-limit: 10

    #####################################################
