# This workflow will install Python dependencies and run tests with pytest, all on Python 3.6

name: Python Webserver CI

on:
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # TODO: write unit tests
      # - name: Test with pytest
      #   run: |
      #     pytest
