# Automatically push a new Sentry release

name: Sentry Release

on:
  pull_request:
    branches: [ master ]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: fractalcomputers
          SENTRY_PROJECT: main-webserver
        with:
          tagName: ${{ github.sha }}
          releaseNamePrefix: main-webserver@
          environment: "prod"
