ignored:
  - DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`.
  - DL3003 # Use WORKDIR to switch to a directory.
  - DL4001 # Either use Wget or Curl but not both.
  - SC2010 # Don't use ls | grep. Use a glob or a for loop with a condition to allow non-alphanumeric filenames.