#
# Global hooks that run on all repositories/subfolders
#
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key

- repo: https://github.com/prettier/prettier
  rev: 2.0.5
  hooks:
    - id: prettier

# To use beautysh, you need to install it via `pip install beautysh`
- repo: local
  hooks:
    - id: beautysh
      name: beautysh
      language: python
      additional_dependencies: [beautysh]
      entry: beautysh
      types: [shell]


#
# Hooks that only run on specific repositories/subfolders
# 
- repo: git://github.com/doublify/pre-commit-clang-format
  rev: master
  hooks:
    - id: clang-format
      name: 'clang-format (for /protocol)'
      files: '^protocol/.*\.(?:c|h)'

- repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
  rev: master
  hooks:
      - id: cmake-format
        name: 'cmake-format (for /protocol)'
        files: '^protocol/.*\.(?:c|h)'

- repo: https://github.com/psf/black
  rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
    - id: black
      name: 'cmake-format (for /main-webserver)'
      files: '^main-webserver/.*\.py'
      language_version: python3

- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
    - id: pylint
      name: 'pylint (for /main-webserver)'
      files: '^main-webserver/.*\.py'
      language_version: python3

- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-vet
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-lint
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-imports
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-cyclo
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
      args: [-over=25]
    - id: validate-toml
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: no-go-testing
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: golangci-lint
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-critic
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-unit-tests
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-build
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'
    - id: go-mod-tidy
      name: 'go-fmt (for /ecs-host-service)'
      files: '^ecs-host-service/.*\.go'    
