matrix:
- name: Markdown/Text
  sources:
  - '**/**/*.md'
  - '**/**/*.txt'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: YAML
  sources:
  - '**/**/*.yml'
  - '**/**/*.yaml'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: Bash
  sources:
  - '**/**/*.sh'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: Python
  sources:
  - '**/**/*.py'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8
 
- name: Go
  sources:
  - '**/**/*.go'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: C/C++
  sources:
  - '**/**/*.c'
  - '**/**/*.cpp'
  - '**/**/*.h'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: JavaScript/TypeScript
  sources:
  - '**/**/*.js'
  - '**/**/*.ts'
  - '**/**/*.tsx'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8

- name: HTML/CSS
  sources:
  - '**/**/*.html'
  - '**/**/*.css'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/workflows/helpers/fractal-wordlist.txt
    encoding: utf-8
