# This workflow will check if the code is linted with Gofmt
name: Go Linter

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    name: Go Linter
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
            
    - name: Check if code is linted with Gofmt
      run: |
        result=$(gofmt -l *.go fractallogger/*.go fractalwebserver/*.go) # gofmt -l returns nothing if all files are formatted, else returns files that need formatting
        if [ "$result" -z ]; then
            (echo "Code is linted with Gofmt" && true)
        else
            (echo "To pass this check please lint the code with Gofmt" && false)
        fi
