name: Publish builds

# Publish on update to master branch
on:
  push:
    branches: [ master ]

env:
  binary-location: build
  binary-name: ecs-host-service
  s3-bucket-uri: s3://fractal-ecs-host-service

jobs:
  s3-publish:
    name: Build and publish to AWS S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-region: [us-east-1]
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        aws-region: ${{ matrix.aws-region }}
    - name: Install Go dependencies
      run: make deps
    - name: Build Go project
      run: make build
    - name: Upload binary to S3
      run: aws s3 cp ${{ env.binary-location }}/${{ env.binary-name }} ${{ env.s3-bucket-uri }}/${{ env.binary-name }}
    - name: Notify Slack
      run: |
        curl -X POST \
        --data-urlencode "payload={\"channel\": \"#general\", \"username\": \"Fractal Bot\", \"text\": \"ECS Host Service build uploaded to S3!\", \"icon_emoji\": \":fractal:\"}" \
        https://hooks.slack.com/services/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
