# Automatically push a new Sentry release

name: Sentry Release

on:
  push:
    branches: [ master ]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: fractalcomputers
          SENTRY_PROJECT: ecs-host-service
        with:
          tagName: ${{ github.sha }}
          environment: "prod"
          
      - name: Notify Slack
        run: |
          curl -X POST \
          --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Sentry\", \"text\": \"ECS Host Service Sentry Release pushed to Sentry.\", \"icon_emoji\": \":sentry:\"}" \
          https://hooks.slack.com/services/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
