name: Monorepo Config
description: Build /config folder into .json files.
branding:
  icon: command
  color: blue
inputs:
  secrets:
    description: JSON object of Fractal secrets
    required: true
outputs:
  config:
    description: JSON object of Fractal config
runs:
  using: docker
  image: Dockerfile

  # Remember that what you declare here gets passed in to the Docker image
  # with the inputs map above. Each key in the input map will be capitalized
  # and prefixed with INPUT_. Look at the bottom of these docs for an example
  # of the environment.

  # The image path fails silently if you get something wrong here. The silent
  # failure looks like a normal run, it just doesn't load your Dockerfile.
  #
  # One more thing... if you have a Dockerfile in the same folder as this file,
  # that Dockerfile will override whatever you set here. This is undocumented,
  # but will cost you a lot of time when it bites you.
  #
  # The path specified here should be relative to this file, not the top of
  # the fractal repository. We expect this file to have an ENTRYPOINT
  # directive, otherwise the args key below will cause an error.

  # The "run.args" here have different functions based on the rest of your
  # configuration. If you have ENTRYPOINT set in your Dockerfile, or the
  # entrypoint: key above, then these will be passed as arguments to the
  # entrypoint command. If you don't have an entrypoint (or something goes
  # silenty wrong with your image: key above), then these will perform the
  # function of the Dockerfile CMD.
  #
  # This can lead to some tricky bugs, so be careful. The error you'll get will
  # be something like "executable file not found in $PATH: unknown". That is
  # because when run.args: is treated like the Dockerfile CMD, then the first
  # element of the run.args: array is supposed to be an executable command.
  #
  # This overloading of run.args: is unfortunate, particularly because image: can
  # fail silently, which means that your Dockerfile's ENTRYPOINT won't be
  # found, which means that run.args: will be treated as a Dockerfile COMMAND as
  # opposed to arguments. Once again, be careful.

  # You don't have to do anything extra to pass this whole environment, as
  # long as you are using the Docker ENTRYPOINT directive in your dockerfile.
  # An enviroment like the one below will be available to your process,
  # including the INPUT_prefixed and capitalized inputs to your Action.
  #
  # {
  #  'ACTIONS_RUNTIME_TOKEN': '*****'
  #  'ACTIONS_CACHE_URL': 'https://artifactcache.actions.githubusercontent.com',
  #  'CI': 'true',
  #  'HOSTNAME': '4a265cb02253',
  #  'GITHUB_ENV': '/github/file_commands/set_env_***',
  #  'PYTHON_PIP_VERSION': '21.1.2',
  #  'HOME': '/github/home',
  #  'GITHUB_EVENT_PATH': '/github/workflow/event.json',
  #  'RUNNER_TEMP': '/home/runner/work/_temp',
  #  'GITHUB_REPOSITORY_OWNER': 'fractal',
  #  'GITHUB_RETENTION_DAYS': '14',
  #  'GPG_KEY': 'E3FF2839C048B25C084DEBE9B26995E310250568',
  #  'GITHUB_HEAD_REF': '',
  #  'GITHUB_GRAPHQL_URL': 'https://api.github.com/graphql',
  #  'GITHUB_API_URL': 'https://api.github.com',
  #  'ACTIONS_RUNTIME_URL': 'https://pipelines.actions.githubusercontent.com/**
  #  'RUNNER_OS': 'Linux',
  #  'GITHUB_WORKFLOW': 'Monorepo Config',
  #  'INPUT_SECRETS': 'neil-secret',
  #  'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/***'
  #  'GITHUB_RUN_ID': '917521391',
  #  'GITHUB_BASE_REF': '',
  #  'GITHUB_ACTION_REPOSITORY': '',
  #  'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin',
  #  'RUNNER_TOOL_CACHE': '/opt/hostedtoolcache',
  #  'GITHUB_ACTION': 'self',
  #  'GITHUB_RUN_NUMBER': '379',
  #  'LANG': 'C.UTF-8',
  #  'GITHUB_REPOSITORY': 'fractal/fractal',
  #  'GITHUB_ACTION_REF': '',
  #  'GITHUB_ACTIONS': 'true',
  #  'PYTHON_VERSION': '3.9.5',
  #  'GITHUB_WORKSPACE': '/github/workspace',
  #  'GITHUB_JOB': 'hello_world_job',
  #  'GITHUB_SHA': '83ce92a46274109e0351ff94477bf4d6316793ba',
  #  'GITHUB_ACTOR': 'neilyio',
  #  'GITHUB_REF': 'refs/heads/neilyio/config/monorepo-level',
  #  'GITHUB_PATH': '/github/file_commands/add_path_***',
  #  'RUNNER_WORKSPACE': '/home/runner/work/fractal',
  #  'PWD': '/github/workspace',
  #  'GITHUB_EVENT_NAME': 'workflow_dispatch',
  #  'GITHUB_SERVER_URL': 'https://github.com',
  #  'PYTHON_GET_PIP_SHA256': '********************************8'
  # }
