repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: detect-private-key

    - repo: https://github.com/petalmd/dockerfile-pre-commit
      rev: v1.0
      hooks:
        - id: dockerlint
          args: [base/Dockerfile.18, base/Dockerfile.20, base/Dockerfile.huge]
