repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-symlinks
        - id: detect-private-key

    - repo: local
      hooks:
        # https://github.com/hadolint/hadolint
        - id: dockerfile-lint
          name: Dockerfile Lint
          language: docker_image
          entry: hadolint
          files: ^base/.*Dockerfile.*$
