AUTH_DOMAIN_URL:
  local: "fractal-dev.us.auth0.com"
  dev: "fractal-dev.us.auth0.com"
  staging: "fractal-staging.us.auth0.com"
  prod: "login.fractal.co"

AUTH_CLIENT_ID:
  local: "j1toifpKVu5WA6YbhEqBnMWN0fFxqw5I"
  dev: "j1toifpKVu5WA6YbhEqBnMWN0fFxqw5I"
  staging: "WXO2cphPECuDc7DkDQeuQzYUtCR3ehjz"
  prod: "Ulk5B2RfB7mM8BVjA3JtkrZT7HhWIBLD"

AUTH_API_IDENTIFIER: "https://api.fractal.co"

CLIENT_CALLBACK_URL: "http://localhost/callback"

AUTH0_DOMAIN:
