AUTH_DOMAIN_URL:
  local: "fractal-dev.us.auth0.com"
  dev: "fractal-dev.us.auth0.com"
  staging: "fractal-staging.us.auth0.com"
  prod: "auth.fractal.co"

AUTH_CLIENT_ID:
  local: "F4M4J6VjbXlT2UzCfnxFaJK2yKJXbxcF"
  dev: "F4M4J6VjbXlT2UzCfnxFaJK2yKJXbxcF"
  staging: "WXO2cphPECuDc7DkDQeuQzYUtCR3ehjz"
  prod: "Ulk5B2RfB7mM8BVjA3JtkrZT7HhWIBLD"

AUTH_API_IDENTIFIER: "https://api.fractal.co"

CLIENT_CALLBACK_URL: "http://localhost/callback"

AUTH0_DOMAIN:
