# Leave as much documentation as you can for these! Some examples of (fake)
# expected values will be helpful.

HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD:

HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING:

REACT_APP_SHA_SECRET_KEY:

APPLE_API_KEY_ID:

APPLE_API_KEY_ISSUER_ID:

APPLE_OAUTH_SECRET:

AUTH0_GHA_CLIENT_SECRET_DEV:

AUTH0_GHA_CLIENT_SECRET_PROD:

AUTH0_GHA_CLIENT_SECRET_STAGING:

AUTH0_REFRESH_TOKEN_DEV:

CLIENTAPP_AMPLITUDE_KEY:

GHA_PERSONAL_ACCESS_TOKEN:

GHA_USERNAME:

GOOGLE_OAUTH_SECRET:

HASURA_GRAPHQL_ACCESS_KEY_CONFIG:

HASURA_GRAPHQL_ACCESS_KEY_DEV:

HASURA_GRAPHQL_ACCESS_KEY_STAGING:

HASURA_GRAPHQL_ACCESS_KEY_PROD:

HEROKU_DEVELOPER_API_KEY:

HEROKU_PIPELINE_NAME:

MACOS_SIGNING_P12_CERTIFICATES_BASE64_ENCODED:

MACOS_SIGNING_P12_CERTIFICATES_BASE64_ENCODED_PASSWORD:

SENTRY_AUTH_TOKEN:

SLACK_EC2_ALERTS_OAUTH_TOKEN:

SLACK_HOOKS_ENDPOINT_DEV:

SLACK_HOOKS_ENDPOINT_STAGING:

SLACK_HOOKS_ENDPOINT_PROD:
