# Leave as much documentation as you can for these! Some examples of (fake)
# expected values will be helpful.

HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD:

HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING:

REACT_APP_SHA_SECRET_KEY:

APPLE_API_KEY_ID:

APPLE_API_KEY_ISSUER_ID:

APPLE_OAUTH_SECRET:

AUTH0_GHA_CLIENT_SECRET_DEV:

AUTH0_GHA_CLIENT_SECRET_PROD:

AUTH0_GHA_CLIENT_SECRET_STAGING:

AUTH0_REFRESH_TOKEN_DEV:

AWS_ACCESS_KEY_ID:

AWS_SECRET_ACCESS_KEY:

AWS_EC2_ACCESS_KEY_ID:

AWS_EC2_SECRET_ACCESS_KEY:

AWS_EC2_S3_ACCESS_KEY_ID:

AWS_EC2_S3_SECRET_ACCESS_KEY:

AWS_EC2_S3_SECRET_ACCESS_KEY_ID:

AWS_S3_ACCESS_KEY_ID:

AWS_S3_SECRET_ACCESS_KEY:

CLIENTAPP_AMPLITUDE_KEY:

CLIENTAPP_AWS_ACCESS_KEY:

CLIENTAPP_AWS_SECRET_KEY:

GHA_PERSONAL_ACCESS_TOKEN:

GHA_USERNAME:

GOOGLE_OAUTH_SECRET:

HASURA_GRAPHQL_ACCESS_KEY_CONFIG:

HASURA_GRAPHQL_ACCESS_KEY_DEV:

HASURA_GRAPHQL_ACCESS_KEY_STAGING:

HASURA_GRAPHQL_ACCESS_KEY_PROD:

HEROKU_ALL_WEBSERVERS_ADMIN_PASSWORD:

HEROKU_ALL_WEBSERVERS_ADMIN_USERNAME:

HEROKU_DEVELOPER_API_KEY:

HEROKU_DEVELOPER_LOGIN_EMAIL:

HEROKU_PIPELINE_NAME:

HOST_SERVICE_LOGZIO_SHIPPING_TOKEN:

MACOS_SIGNING_CERTIFICATE:

MACOS_SIGNING_CERTIFICATE_PASSWORD:

SENTRY_AUTH_TOKEN:

SLACK_EC2_ALERTS_OAUTH_TOKEN:

SLACK_HOOKS_ENDPOINT:

WEBSERVER_LOGZIO_SHIPPING_TOKEN:
