# client-applications/config/contstants.js: WhistNodeEnvironments
NODEJS:
  local: "local"
  dev: "development"
  staging: "staging"
  prod: "prod"

# client-applications/config/contstants.js: WhistEnvironments
ENV:
  local: "local"
  dev: "dev"
  staging: "staging"
  prod: "prod"
