# client-applications/desktop/config/contstants.js: FractalNodeEnvironments
NODEJS:
  local: "local"
  dev: "development"
  staging: "staging"
  prod: "prod"

# client-applications/desktop/config/contstants.js: FractalEnvironments
ENV:
  local: "local"
  dev: "dev"
  staging: "staging"
  prod: "prod"
