# client-applications/config/build.js
ICON_FILE_NAME:
  local: "icon_local"
  dev: "icon_dev"
  staging: "icon_staging"
  prod: "icon"

EXECUTABLE_NAME:
  local: "Whist (local)"
  dev: "Whist (development)"
  staging: "Whist (staging)"
  prod: "Whist"

# client-applications/config/paths.js
CLIENT_LOG_FILE_NAME: "client.log"
PROTOCOL_LOG_FILE_NAME: "protocol.log"

CLIENT_PERSISTENCE_FOLDER_NAME:
  local: "Electron"
  dev: "fractal"
  staging: "fractal"
  prod: "fractal"

CLIENT_LOG_FOLDERNAME: "logs"

PROTOCOL_FILE_NAME:
  macos: "_Fractal"
  win32: "Whist.exe"
  linux: "Whist"

PROTOCOL_FOLDER_PATH:
  macos: "../../MacOS"
  win32: "../../protocol-build/client"
  linux: "../../../protocol-build/client"
