DB_URL_STAGING:
DB_URL_PROD:
github_token:
DB_URL_DEV:
BRANCH:
CONFIG_DB_URL:
DATABASE_URL:
HEROKU_APP_ID:
HEROKU_APP_NAME:
HEROKU_RELEASE_CREATED_AT:
HEROKU_RELEASE_VERSION:
HEROKU_SLUG_COMMIT:
HEROKU_SLUG_DESCRIPTION:
NUM_WORKERS:
SECRET_KEY:
SENTRY_DSN:
SLACK_BOT_OAUTH_TOKEN:
WORKER_CONCURRENCY:
