DB_URL_STAGING:
DB_URL_PROD:
github_token:
DB_URL_DEV:
BRANCH:
CONFIG_DB_URL:
DATABASE_URL:
HEROKU_APP_ID:
HEROKU_APP_NAME:
HEROKU_RELEASE_CREATED_AT:
HEROKU_RELEASE_VERSION:
HEROKU_SLUG_COMMIT:
HEROKU_SLUG_DESCRIPTION:
NUM_WORKERS:
SECRET_KEY:
SENTRY_DSN:
SLACK_BOT_OAUTH_TOKEN:
WORKER_CONCURRENCY:
# A preshared client commit hash that is accepted along with the
# client commit hash corresponding to the active AMI in the database
# in dev environment. Used for enabling client app developers to be able to
# connect to dev environment without updating entries in the development
# database to match their local commit hash values.
CLIENT_COMMIT_HASH_DEV_OVERRIDE: "local_dev"