CLIENT_DOWNLOAD_URL:
  local:
    macos: "https://fractal-chromium-macos-dev.s3.amazonaws.com/Fractal.dmg"
    win32: "https://fractal-chromium-windows-dev.s3.amazonaws.com/Fractal.exe"
    linux: "https://fractal-chromium-linux-dev.s3.amazonaws.com/Fractal.AppImage"
  dev:
    macos: "https://fractal-chromium-macos-dev.s3.amazonaws.com/Fractal.dmg"
    win32: "https://fractal-chromium-windows-dev.s3.amazonaws.com/Fractal.exe"
    linux: "https://fractal-chromium-linux-dev.s3.amazonaws.com/Fractal.AppImage"
  staging:
    macos: "https://fractal-chromium-macos-staging.s3.amazonaws.com/Fractal.dmg"
    win32: "https://fractal-chromium-windows-staging.s3.amazonaws.com/Fractal.exe"
    linux: "https://fractal-chromium-linux-staging.amazonaws.com/Fractal.AppImage"
  production:
    macos: "https://fractal-chromium-macos-prod.s3.amazonaws.com/Fractal.dmg"
    win32: "https://fractal-chromium-windows-prod.s3.amazonaws.com/Fractal.exe"
    linux: "https://fractal-chromium-linux-prod.s3.amazonaws.com/Fractal.AppImage"

WEBSERVER_URL:
  local: "http://127.0.0.1:7730"
  dev: "https://dev-server.fractal.co"
  staging: "https://staging-server.fractal.co"
  production: "https://prod-server.fractal.co"

FRONTEND_URL:
  local: "http://localhost:3000"
  dev: "dev.fractal.co"
  staging: "staging.fractal.co"
  production: "production.fractal.co"
