# workflows/linting.yml
#
# Website: Linting
# Lint website using eslint.

name: "Website: Linting"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev

jobs:
    website-linting-main:
        name: Lint Website
        runs-on: ubuntu-20.04

        env:
            CI: true
            NPM_TOKEN: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}

        steps:
            - name: Check out Git Repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

            - name: Install Node.js 14
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14

            - name: Run npm install
              run: |
                  npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}"
                  npm install

            - name: Check if code follows ESLint standards
              run: npm run lint-check
