rules:
  - name: add-customer-id-claim
    script: ./rules/add-customer-id-claim.js
    stage: login_success
    enabled: true
    order: 2
  - name: add-subscription-status-claim
    script: ./rules/add-subscription-status-claim.js
    stage: login_success
    enabled: true
    order: 3
  - name: create-customer
    script: ./rules/create-customer.js
    stage: login_success
    enabled: true
    order: 1
rulesConfigs: []
hooks: []
pages:
  - name: login
    enabled: true
    html: ./pages/login.html
resourceServers:
  - name: Whist API
    identifier: https://api.fractal.co
    allow_offline_access: true
    enforce_policies: true
    scopes:
      - value: admin
        description: Whist administrative resource(s)
      - value: backend
        description: Granted to trusted Whist backend(s)
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: Chromium Auth
    allowed_clients: []
    allowed_origins:
      - chrome-extension://ahjecglibcdgcpmdpehkgkpkmcapnnle
    app_type: spa
    callbacks:
      - https://com.whist.auth0/callback
      - https://fractal-dev.us.auth0.com/callback
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: The Whist frontend, baked into Brave (Chromium).
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins: []
databases: []
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Chromium Auth
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
      client_id: 581514545734-4r65pae9m63dci2rq6isstvaapuqp85l.apps.googleusercontent.com
      client_secret: "##GOOGLE_OAUTH_SECRET##"
      allowed_audiences: []
tenant:
  default_audience: ""
  default_directory: ""
  enabled_locales:
    - en
    - bs
    - bg
    - zh-CN
    - zh-TW
    - hr
    - cs
    - da
    - nl
    - et
    - fi
    - fr-CA
    - fr
    - de
    - el
    - hi
    - hu
    - is
    - id
    - it
    - ja
    - ko
    - lv
    - lt
    - nb
    - pl
    - pt-BR
    - pt-PT
    - ro
    - ru
    - sr
    - sk
    - sl
    - es
    - sv
    - th
    - tr
    - uk
    - vi
  flags:
    new_universal_login_experience_enabled: true
    universal_login: true
    dashboard_ui_next: true
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: Whist Technologies, Inc.
  picture_url: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
  support_email: support@whist.com
  support_url: https://whist.com/contact
  universal_login:
    colors:
      page_background: "#ffffff"
      primary: "#4f35de"
roles:
  - name: Developer
    description: Whist developers
    permissions:
      - permission_name: admin
        resource_server_identifier: https://api.fractal.co
branding:
  colors:
    page_background: "#ffffff"
    primary: "#4f35de"
  logo_url: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
prompts:
  universal_login_experience: new
  identifier_first: true
migrations: {}
actions: []
triggers: {}
organizations: []
