rules:
  - name: create-customer
    script: ./rules/create-customer.js
    stage: login_success
    enabled: true
    order: 1
  - name: add-customer-id-claim
    script: ./rules/add-customer-id-claim.js
    stage: login_success
    enabled: true
    order: 2
  - name: add-subscription-status-claim
    script: ./rules/add-subscription-status-claim.js
    stage: login_success
    enabled: true
    order: 3
rulesConfigs: []
hooks: []
pages:
  - name: login
    enabled: true
    html: ./pages/login.html
resourceServers:
  - name: Whist API
    identifier: "##WHIST_AUTHENTICATION_API##"
    allow_offline_access: true
    enforce_policies: true
    scopes:
      - value: admin
        description: Whist administrative resource(s)
      - value: backend
        description: Granted to trusted Whist backend(s)
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_dialect: access_token
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: Whist
    allowed_clients: []
    app_type: native
    callbacks: @@ALLOWED_AUTH0_CALLBACKS@@
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: The Whist desktop application(s)
    grant_types:
      - authorization_code
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: none
databases: []
connections:
  - name: apple
    strategy: apple
    enabled_clients: []
    is_domain_connection: false
    options:
      kid: D3T9SSLTY5
      name: true
      email: true
      scope: name email
      team_id: 757Z8TDNJL
      client_id: com.whisttechnologies.whistauth
      app_secret: "##APPLE_OAUTH_SECRET##"
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Whist
    is_domain_connection: false
    options:
      email: true
      gmail: false
      orkut: false
      scope:
        - email
        - profile
      sites: false
      tasks: false
      blogger: false
      profile: true
      youtube: false
      calendar: false
      contacts: false
      analytics: false
      client_id: 581514545734-4r65pae9m63dci2rq6isstvaapuqp85l.apps.googleusercontent.com
      moderator: false
      coordinate: false
      picasa_web: false
      google_plus: false
      google_books: false
      google_drive: false
      spreadsheets: false
      client_secret: "##GOOGLE_OAUTH_SECRET##"
      document_list: false
      latitude_best: false
      latitude_city: false
      url_shortener: false
      webmaster_tools: false
      chrome_web_store: false
      allowed_audiences: ""
      adsense_management: false
      google_drive_files: false
      coordinate_readonly: false
      google_cloud_storage: false
      content_api_for_shopping: false
      google_affiliate_network: false
tenant:
  default_audience: ""
  default_directory: ""
  enabled_locales:
    - bs
    - bg
    - zh-CN
    - zh-TW
    - hr
    - cs
    - da
    - nl
    - en
    - et
    - fi
    - fr-CA
    - fr
    - de
    - el
    - hi
    - hu
    - is
    - id
    - it
    - ja
    - ko
    - lv
    - lt
    - nb
    - pl
    - pt-BR
    - pt-PT
    - ro
    - ru
    - sr
    - sk
    - sl
    - es
    - sv
    - th
    - tr
    - uk
    - vi
  flags:
    new_universal_login_experience_enabled: true
    universal_login: true
    dashboard_ui_next: true
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  friendly_name: Whist Technologies, Inc.
  picture_url: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
  support_email: support@whist.com
  support_url: https://whist.com/contact
  universal_login:
    colors:
      page_background: "#ffffff"
      primary: "#4f35de"
roles:
  - name: Developer
    description: Whist developers
    permissions:
      - permission_name: admin
        resource_server_identifier: "##WHIST_AUTHENTICATION_API##"
branding:
  colors:
    page_background: "#ffffff"
    primary: "#4f35de"
  logo_url: https://whist-brand-assets.s3.amazonaws.com/png/new+logo/FullColorShaded_blue.png
prompts:
  universal_login_experience: new
  identifier_first: true
migrations:
  issue_opaque_access_tokens: false
actions: []
triggers: {}
organizations: []
