repos:
-   repo: git://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    -   id: clang-format
-   repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: master
    hooks:
    -   id: cmake-format
