# dependabot.yml
#
# Configuration file for Dependabot on the fractal/website repository

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/" # default location of `.github/workflows`
    schedule:
      interval: "monthly" # runs on the first day of each month
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/" # looks for package.json and [package-lock/yarn].lock file in this directory
    schedule:
      interval: "monthly" # runs on the first day of each month
    open-pull-requests-limit: 10
