# This workflow builds and pushes container images to ECR

name: Build Container Images

on:
  push:
    branches: [ master , dev ]

env:
  apps: ('base')
  version: '18'
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  # Linux scripts
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup fractal user
        run: |
          sudo useradd fractal || echo "fractal user already exists"
          echo 'fractal:password1234567.' | sudo chpasswd && echo "Set password"
          sudo mkhomedir_helper fractal
          echo $HOME

      - name: Run build dockerfile
        run: for i in "${apps[@]}"
             do
                ./build.sh $i $version
                ./push.sh $i $version

             done
        working-directory: linux
        env:
          LOCAL: yes
          FRACTAL_GITHUB_ACTION: yes
