# Workflow to build Docker images for basic testing
name: Dockerfiles Building

on:
  pull_request:
    branches: [ master, dev ]

env:
  apps: >
    base
    browsers/chrome
    browsers/firefox
    browsers/brave
    productivity/slack
    productivity/discord
    productivity/notion
    creative/blender
    creative/blockbench
    creative/figma
    creative/gimp

jobs:
    build-dockerfiles:
        name: Build Dockerfiles
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
                  token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
                  submodules: recursive

            - name: Build debug protocol
              run: ./build_protocol.sh

            - name: Build container images
              run: |
                for app in ${{ env.apps }}
                do
                  ./build_container_image.sh $app
                done
                
