# Workflow to build Docker images for basic testing

name: Dockerfiles Building

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  docker-build-base-ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
          submodules: recursive

      - name: Build the Fractal protocol dev branch
        run: cd base/protocol && git checkout origin/dev && server/linux-server-setup.sh && cmake . && make -j

      - name: Build the Ubuntu 20.04 Base Image
        run: cd base && docker build . --file Dockerfile.20 --tag base-ubuntu20.04:$(date +%s)

      - name: Build the Ubuntu 20.04 Google Chrome Image
        run: cd browsers/chrome && docker build . --file Dockerfile.20 --tag chrome-ubuntu20.04:$(date +%s)

      - name: Build the Ubuntu 20.04 Mozilla Firefox Image
        run: cd browsers/firefox && docker build . --file Dockerfile.20 --tag firefox-ubuntu20.04:$(date +%s)

      - name: Build the Ubuntu 20.04 Slack Image
        run: cd productivity/slack && docker build . --file Dockerfile.20 --tag slack-ubuntu20.04:$(date +%s)

      - name: Build the Ubuntu 20.04 Blender Image
        run: cd creative/blender && docker build . --file Dockerfile.20 --tag blender-ubuntu20.04:$(date +%s)

      - name: Build the Ubuntu 20.04 Blockbench Image
        run: cd creative/blockbench && docker build . --file Dockerfile.20 --tag blockbench-ubuntu20.04:$(date +%s)
