# This workflow ensures that we only push protocol subrepo commits on the
# master branch to the master branch of container-images. In addition, we
# require that the subrepo commit being pushed is actually the _latest_ commit
# on master.
name: Submodule Commit Verification

on:
  pull_request:
    branches: [ master ]

jobs:
  verify-submodule-branches:
    name: Verify Submodule Commits
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
            token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
            submodules: recursive
 
      - name: Get Commit Hashes of Latest Master and Current Commit
        run: |
          cd base/protocol
          echo "LATEST_MASTER=$(git rev-parse master)" >> $GITHUB_ENV
          echo "CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Verify Hashes are Equal
        run: |
            if [ "$LATEST_MASTER" = "$CURRENT_COMMIT" ] 
            then 
              echo "Current protocol subrepo commit matches latest master."
              exit 0
            else 
              echo "Current protocol subrepo commit does not match latest master!"
              printf "Current protocol commit: %s\n" "$CURRENT_COMMIT"
              printf "Latest master commit: %s\n" "$LATEST_MASTER"
              exit -1
            fi
