repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict

    - repo: https://github.com/psf/black
      rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
        - id: black
          language_version: python3 # Should be a command that runs Python 3.6+
