version: "3.8"

services:

    postgres_db:
        image: postgres:12.5
        ports:
            - "9999:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        networks:
            - primary

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres_db
    networks:
      # docker networks make sure web can find redis
      - primary
    volumes:
      - ..:/app
      - $HOME/.aws:/.aws
    command: web
    ports:
      - "7730:7730" # Proxy 7730 (should match $PORT) on localhost
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /.aws/credentials
      DATABASE_URL: ${DATABASE_URL}
      PORT: 7730
      APP_GIT_BRANCH: ${APP_GIT_BRANCH}
      APP_GIT_COMMIT: ${APP_GIT_COMMIT}

networks:
    primary:
