version: "3.8"

x-app: &base-app
  build:
    context: ..
    dockerfile: docker/Dockerfile
  depends_on:
    - redis
  env_file: .env
  networks:
    - primary

services:
  redis:
    # Matches version being used by staging as of 2020-07-08
    image: madflojo/redis-tls # redis:5.0.8
    ports:
      - "7810:6379" # Proxy redis on localhost:7810
    networks:
      - primary
    volumes:
      - ../TMP_SAVE:/certs

  web:
    <<: *base-app
    command: web
    ports:
      - "7730:7730" # Proxy 7730 (should match $PORT) on localhost
    environment:
      REDIS_TLS_URL: rediss://redis
      HOT_RELOAD: ${HOT_RELOAD}
      PORT: 7730
    volumes:
      - ..:/app

  celery:
    <<: *base-app
    command: celery
    environment:
      - REDIS_TLS_URL=rediss://redis
      - AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
    volumes:
      - ..:/app
      - $HOME/.aws:/.aws

# TODO use a local DB (as commented out below) instead of the staging/production DB
#   db:
#     image: postgres:9.4
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     networks:
#       - primary
#
# volumes:
#   db-data:

networks:
  primary:
