[build]
  # https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
  # https://docs.netlify.com/configure-builds/environment-variables/#git-metadata
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
