# workflows/auth0-check-pr.yml
#
# Auth0: Check PR
# Check an Auth0 PR to ensure that our service authentication and configuration is valid.

name: "Auth0: Check PR"

on:
  pull_request:
    paths:
      - "auth0/**"
      - "!auth0/README.md"
      - "!auth0/**/README.md"
      - ".github/workflows/auth0-check-pr.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: auth0-check-pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Check that our Auth0 deployment setup works by attempting to retrieve the current upstream schema
  auth0-verify-tenant-schema-retrieval:
    name: "Auth0: Verify Tenant Schema Retrieval for ${{ matrix.environment.name }}"
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        environment:
          - name: Dev
            ref: /refs/heads/dev
            branch: dev
          - name: Staging
            ref: /refs/heads/staging
            branch: staging
          - name: Prod
            ref: /refs/heads/prod
            branch: prod

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"

      - name: Install Dependencies
        working-directory: backend/auth0
        run: yarn install

      - name: Dump the Upstream Auth0 Tenant
        working-directory: backend/auth0
        env:
          AUTH0_CLIENT_SECRET: ${{ secrets[format('AUTH0_GHA_CLIENT_SECRET_{0}', matrix.environment.branch)] }}
          GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
          APPLE_OAUTH_SECRET: ${{ secrets.APPLE_OAUTH_SECRET }}
        run: yarn dump:${{ matrix.environment.branch }}
