# workflows/backend-services-check-pr.yml
#
# Backend Services: Check PR
# Checks a Backend Services PR to make sure it builds and matches code standards.

name: "Backend Services: Check PR"

on:
  push:
    # Trigger runs on our default branch, `dev`, to upload code coverage reports to Codecov
    branches:
      - dev
    paths:
      - "backend/services/**"
      - "!backend/services/README.md"
      - "backend/webserver/db_migration/schema.sql"
      - ".github/workflows/backend-services-check-pr.yml"
  pull_request:
    paths:
      - "backend/services/**"
      - "!backend/services/README.md"
      - "backend/webserver/db_migration/schema.sql"
      - ".github/workflows/backend-services-check-pr.yml"
  workflow_dispatch:

jobs:
  # Building
  # Check that the Host Service builds.
  backend-services-check-pr-building:
    name: Building
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          # Get the whole git history. We must do this because the
          # Codecov requires the full history to upload coverage reports
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.17"

      - name: Authenticate Go commands with GitHub
        env:
          GH_USERNAME: ${{ secrets.GHA_USERNAME }}
          GH_PAT: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
        run: git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/

      # Set up AWS credentials to allow upload and download from S3
      # for user config integration test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_USER_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Check go project (clean, build, vet, format, lint, test, docs)
      - name: Check Go Project
        working-directory: backend/services
        env:
          HEROKU_USER: developers@whist.com
          HEROKU_APIKEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Add Go to path
          PATH=$PATH:~/go/bin

          # This checks for building, vet, format and lint, and will fail if unformatted
          make check
