# workflows/bashscripts-linting.yml
#
# Bash Scripts: Linting
# Lint and enforce good practices for Bash Scripts using Shellcheck.

name: "Bash Scripts: Linting"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
        paths:
            - "**/*.sh"
            - ".github/workflows/bashscripts-linting.yml"
    workflow_dispatch:

jobs:
    bashscripts-linting-main:
        name: Lint Bash Scripts
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Run ShellCheck to Check for Bash Script Good Practices
              uses: ludeeus/action-shellcheck@master
              with:
                  check_together: "yes" # Tell Shellcheck to check all files at once

            - name: Check that All Bash Scripts Start with "#!/bin/bash"
              run: |
                  find . -name '*.sh' -exec bash -c 'for file do

                    if [[ "`head -c 11 $file`" = "#!/bin/bash" ]]; then
                        echo "[#!/bin/bash -> Present] $file"
                    else
                        echo "[#!/bin/bash -> NOT FOUND] $file" && exit 1
                    fi
                  done' -- {} +

            - name: Check that All Bash Scripts Contain "-set -Eeuo pipefail"
              run: |
                  find . -name '*.sh' -exec bash -c 'for file do
                      if grep -q "-set -Eeuo pipefail" "$file"; then
                        echo "[-set -Eeuo pipefail -> Present] $file"
                      else
                          echo "[-set -Eeuo pipefail -> NOT FOUND] $file" && exit 1
                      fi
                  done' -- {} +





