# workflows/browser-builder.yml
#
# Browser Builder: Build Brave Browser
# Spins up an AWS macOS EC2 instance to compile Brave Browser

name: "Browser Builder: Build Brave Browser"

# Only run on workflow_dispatch and if a client-side piece of Fractal is modified
on:
  push:
    branches:
      - dev
    paths:
      - "client-applications/**"
      - "core-ts/**"
      - "microservices/**"
      - "protocol/**"
  pull_request:
    branches:
      - dev # TODO: For testing, need to remove
  workflow_dispatch:

jobs:
  build-and-publish-brave-browser:
    name: Compile Brave Browser on ${{ matrix.runners.name }}
    runs-on: ${{ matrix.runners.os }}
    defaults:
      run:
        shell: ${{ matrix.runners.shell }}

    strategy:
      matrix:
        runners:
          # - name: macOS (X86_64)
          #   os: [self-hosted, macOS, X64] # MacStadium Intel i7 3.2GHz 6-cores 32GB RAM
          #   shell: bash --noprofile --norc -eo pipefail {0}
          # - name: macOS (ARM64)
          #   os: [self-hosted, macOS, ARM64] # MacStadium Apple Silicon M1 8GB RAM
          #   shell: /usr/bin/arch -arch arm64e /bin/bash {0}
          - name: macOS (GHA) # TODO: For testing in GHA, need to remove
            os: macos-10.15
            shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      ##################################### CONFIG STEPS START ###################################

      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          repository: brave/brave-browser
          path: brave-browser

      # Speed up npm: https://github.com/brave/brave-browser/wiki/macOS-Development-Environment
      - name: Turn macOS Spotlight Off to Speed Up Build
        working-directory: brave-browser
        run: touch .metadata_never_index && killall Finder

      # Brave needs to be built with NodeJS 12.x and npm 6.x, as per:
      # https://github.com/brave/brave-browser/wiki/macOS-Development-Environment
      - name: Downgrade to NodeJS 12
        run: |
          # downgrade to NodeJS 12.x and npm 6.x for Brave requirements
          brew install node@12

          # link new NodeJS version with the compilers
          echo 'export PATH="/usr/local/opt/node@12/bin:$PATH"' >> /Users/runner/.bash_profile
          export LDFLAGS="-L/usr/local/opt/node@12/lib"
          export CPPFLAGS="-I/usr/local/opt/node@12/include"

          # verifiy versions
          node -v
          npm -v

      # This is necessary to solve this issue in building:
      # https://stackoverflow.com/questions/52176570/deprecationwarning-with-readplist-attributeerror
      - name: Downgrade Python to 3.6
        run: |
          # downgrade to Python 3.6.x
          brew unlink python
          brew switch python 3.6.5

          # verify version
          python --version
          python3 --version

      - name: Run npm install
        working-directory: brave-browser
        run: npm install

      ############################################################################################
      #################################### BUILDING STEPS START ##################################

      # This takes 30-45 minutes to run
      # The Chromium source is downloaded, which has a large history
      - name: Run npm init
        working-directory: brave-browser
        run: npm run init

      # Build options are:
      # npm run build           --> standard build with Chromium components mode enabled
      # npm run build Release   --> standard build for production use, without debug symbols
      # npm run build Static    --> statically linked build (takes longer to build, but starts faster)
      # npm run build Debug     --> standard build with debug mode enabled
      - name: Build Brave Browser in Debug Mode
        working-directory: brave-browser
        run: npm run build

      ############################################################################################
      ################################### PUBLISHING STEPS START #################################

      ############################################################################################
      ################################# NOTIFICATIONS STEPS START ################################

      - name: Checkout Fractal Git Repository
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && failure() }}
        uses: actions/checkout@v2

      - name: Setup Python-based Notifications
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && failure() }}
        working-directory: .github/workflows/helpers
        run: ./notifications/setup_notifications.sh

      - name: Notify Slack on Workflow Failure (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && failure() }}
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
          SLACK_CHANNEL = "#alerts-prod"
          BODY = f"@releases :rotating_light: Failed to build and deploy Brave Browser for ${{ matrix.runners.os }} to AWS S3, investigate immediately :rotating_light: (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY)

  ################################################################################################
  ################################################################################################

  notify-slack:
    name: Notify Slack on Workflow Success
    needs: [build-and-publish-brave-browser]
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && success() }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup Python-based Notifications
        working-directory: .github/workflows/helpers
        run: ./notifications/setup_notifications.sh

      - name: Notify Slack on Workflow Success (Only on Push/Workflow_dispatch Events)
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
          SLACK_CHANNEL = "#alerts-prod"
          TITLE = ":brave: Fractal Brave Browser Built and Deployed :brave:"
          BODY = f"Fractal Brave Browser for macOS build and deployed to Production via upload to AWS S3 (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
