# workflows/client-applications-check-pr.yml
#
# Client Applications: Check PR
# Checks a client-applications PR for linting and building success.

name: "Client Applications: Check PR"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
            - project/**
        paths:
            - "client-applications/**"
            - "!client-applications/README.md"
            - ".github/workflows/client-applications-linting.yml"
    workflow_dispatch:

jobs:
    # Linting
    # Checks for formatting using ESlint.
    client-applications-check-pr-linting:
        name: Linting
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Run yarn -i in /desktop
              working-directory: client-applications/desktop
              run: yarn -i

            - name: Check if code follows ESLint standards
              working-directory: client-applications/desktop
              run: yarn lint-check

    # Building
    # Check that the Client Applications build.
    client-applications-check-pr-building:
        name: Building




        runs-on: ubuntu-20.04

        steps:





