# Workflow to lint an Electron app with Prettier

name: Lint client-applications

on:
  pull_request:
    branches: [master, dev]
    paths:
      - "client-applications/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run yarn -i in /desktop
        run: cd client-applications/desktop && yarn -i

      - name: Format with Prettier in /desktop
        run: cd client-applications/desktop && yarn format

      - name: Check if code is linted with Prettier
        run: |
          result=$(cd client-applications/desktop && yarn format-check) # checks if code is linted via prettier --check
          if [ "$result" -ne "0" ]; then
            (echo "To pass this check please lint the code with Prettier" && false)
          else
            (echo "Code is linted with Prettier" && true)
          fi

      - name: Check if code follows ESLint standards
        run: |
          result=$(cd desktop && yarn lint-check) # checks if code is linted via prettier --check
          if [ "$result" -ne "0" ]; then
            (echo "To pass this check please lint the code with ESLint or update .eslintrc.js to ignore unwanted checks" && false)
          else
            (echo "Code is linted with ESLint" && true)
          fi
