# workflows/container-images-acquire-unity-activation-file.yml
#
# Container Images: Acquire Unity Activation File
# Acquire a Unity activation file and upload it as a GitHub artifact.

name: "Container Images: Acquire Unity Activation File"

# The Unity activation file only needs to be retrieved once per Unity version
# we use, so we only run this workflow manually
# For context, see: https://unity-ci.com/docs/github/activation
on: workflow_dispatch

jobs:
    container-images-acquire-unity-activation-file-main:
        name: Acquire Unity Activation File and Upload It as a GitHub Artifact
        runs-on: ubuntu-20.04

        steps:
            # Request manual activation file
            - name: Request Manual Unity Activation File
              id: getManualLicenseFile
              uses: webbertakken/unity-request-manual-activation-file@v1.1
              with:
                  unityVersion: 2019.2.11f1 # change this version to match the one used in the Fractal Unity containers

            # Upload artifact (Unity_v20XX.X.XXXX.alf)
            - name: Expose as GitHub Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.getManualLicenseFile.outputs.filePath }}
                  path: ${{ steps.getManualLicenseFile.outputs.filePath }}

            - name: Notify Slack
              run: |
                  curl -X POST \
                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"New Unity Activation File Acquired and Uploaded to GitHub Artifact via Manually Triggering GitHub Actions Workflow.\", \"icon_emoji\": \":fractal:\"}" \
                  ${{ secrets.SLACK_HOOKS_ENDPOINT }}
