# workflows/container-images-build-images.yml
#
# Container Images: Build Images
# Build docker images to test that they actually build.

name: "Container Images: Build Images"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
            - project/**
        paths:
            - "container-images/**"
            - ".github/workflows/container-images-build-images.yml"
            - "!container-images/README.md"
            - "!container-images/run_container_image.sh"
            - "!container-images/run_local_container_image.sh"
            - "!container-images/run_remote_container_image.sh"
    workflow_dispatch:

jobs:
    container-images-build-images-main:
        name: Build Docker Images for Testing
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
                  submodules: recursive

            - name: Install the AWS CLI to build the protocol on Linux
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
              run: |
                  curl -Ss "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip -q awscliv2.zip
                  sudo ./aws/install --update
                  install -Dv /dev/null ~/.aws/credentials
                  echo "[default]" > ~/.aws/credentials
                  echo "\"aws_access_key_id = $AWS_ACCESS_KEY_ID\"" >> ~/.aws/credentials
                  echo "\"aws_secret_access_key = $AWS_SECRET_ACCESS_KEY\"" >> ~/.aws/credentials

            - name: Test aws cli
              run: aws s3 cp s3://fractal-protocol-shared-libs/shared-libs.tar.gz fractal-protocol-shared-libs.tar.gz

            - name: Build the protocol
              run: ./protocol/build_protocol.sh

            - name: Uninstall the AWS CLI
              run: |
                rm ~/.aws/credentials
                sudo rm -rf /usr/local/aws-cli/


            - name: Configure AWS CLI # To get and install GRID driver
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Walk repo to find all dockerfiles and store path as env variable
              run: echo "apps=$(./container-images/find_images_in_git_repo.sh)" >> $GITHUB_ENV

            - name: Build container images
              run: |
                  for app in ${{ env.apps }}
                  do
                    ./container-images/build_container_image.sh $app
                  done
