# workflows/core-ts-linting.yml
#
# Core TypeScript Library: Check PR
# Checks a Core-TS PR for linting and testing success.

name: "Core TypeScript Library: Check PR"

on:
    pull_request:
        branches:
            - prod
            - staging
            - dev
        paths:
            - "core-ts/**"
            - "!core-ts/README.md"
            - ".github/workflows/core-ts-check-pr.yml"
    workflow_dispatch:

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 15

            - name: Run npm install
              working-directory: core-ts
              run: npm install

            - name: Check if Code Follows ESLint Standards
              working-directory: core-ts
              run: npm run lint-check

    test:
        name: Testing
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 15

            - name: Run npm install
              working-directory: core-ts
              run: npm install

            - name: Run core-ts test suite
              working-directory: core-ts
              run: npm run test
