name: "Monorepo Config"

on:
  workflow_dispatch:

jobs:
  parse_config:
    runs-on: ubuntu-latest
    name: Parse /config schemas
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - name: Parse /config schemas
        uses: ./.github/actions/monorepo-config
        with:
          secrets: "${{ toJSON(secrets) }}"

      # We need to give the "uses" path relative to the monorepo root.
      # The path also requires the leading ./
      # These will become available to the action as env variables.
      # Note that GitHub will automatically capitalize the variable on the
      # action side, and prefix it with INPUT_
