# workflows/core-ts-linting.yml
#
# Core TypeScript Library: Check PR
# Checks a Core-TS PR for linting and testing success.

name: "Core TypeScript Library: Check PR"

on:
    pull_request:
        paths:
            - "core-ts/**"
            - "!core-ts/README.md"
            - ".github/workflows/core-ts-check-pr.yml"
    workflow_dispatch:

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 15
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: 15

            - name: Run yarn install
              working-directory: core-ts
              run: yarn install

            - name: Check if Code Follows ESLint Standards
              working-directory: core-ts
              run: yarn run lint-check

    test:
        name: Testing
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 15
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: 15

            - name: Run yarn install
              working-directory: core-ts
              run: yarn install

            - name: Run core-ts test suite
              working-directory: core-ts
              run: yarn run test
