# workflows/database-migration.yml
#
# Main Webserver: Migrate Database
# Compare the schema of the live database with
# main-webserver/db-migration/schema.sql
# If schema changes are detected, perform the migration
# on PR merge

name: "Database Migration"

on:
    push:
        branches:
            - master
            - staging
            - dev
    pull_request:
        branches:
            - master
            - staging
            - dev
    workflow_dispatch:

jobs:
    run-migra-diff:
        name: Run Migra Diff
        runs-on: ubuntu-20.04

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_ISSUE: ${{ github.event.number }}
            GITHUB_BRANCH: ${{ github.base_ref }}
            HEROKU_DB_KEY: "DATABASE_URL"
            HEROKU_API_TOKEN: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
            SERVER_DEV: "fractal-dev-server"
            SERVER_STAGING: "fractal-staging-server"
            SERVER_MASTER: "fractal-prod-server"
            SCRIPT_DIFF: "main-webserver/db_migration/schema_diff.py"
            PATH_HELPERS: ".github/workflows/helpers"
            PATH_SCRIPTS: "main-webserver/db_migration"
            PATH_CURRENT: "../temporary_db_schema.sql"
            PATH_MERGING: "main-webserver/db_migration/schema.sql"
            PATH_DIFF: "../temporary_diff_file.sql"
            TITLE_ERROR: >-
                An error occured while comparing the database schema.
            TITLE_NO_CHANGES: >-
                Schema is unchanged, no database migration needed.
            TITLE_SAFE_CHANGES: >-
                There's some changes to be made to the schema!
            TITLE_UNSAFE_CHANGES: >-
                This PR introduces destructive changes to the schema!
            TITLE_INVALID_CHANGES: >-
                This PR will not migrate successfully.
            BODY_ERROR: >-
                The diff tool `migra` exited with an error.
            BODY_NO_CHANGES: >-
                Carry on!
            BODY_SAFE_CHANGES: >-
                The SQL commands below will perform the migration.
            BODY_UNSAFE_CHANGES: >-
                The schema diff produced some unsafe commands, which can be
                dangerous to run on the database.


                Remember these will be run automatically upon merge, so be sure
                to review these changes extra carefully.


                The SQL commands below will perform the migration.
            BODY_INVALID_CHANGES: >-
                The schema diff did not pass the migration test. The following
                SQL commands will not be applied properly to the database.

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2
              
            - name: Random new step
              run: |
                  echo "RANDOM NEW STEP"
