# workflows/deploy-auth0-hooks.yml
#
# Microservices: deploy Auth0 hooks
# Builds and deploys hooks to Auth0

name: Deploy hook microservices to Auth0
on:
    push:
        branches: [dev, staging, prod]

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./microservices/auth0
        steps:
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Set Auth0 Client secret
              id: set-client-secret
              run: |
                  # Grab branch_name from detect-branch
                  BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}

                  if [ "$BRANCH_NAME" == "prod" ]; then
                      AUTH0_SECRET=${{ secrets.PROD_AUTH0_CLIENT_SECRET }}
                  elif [ "$BRANCH_NAME" == "staging" ]; then
                      AUTH0_SECRET=${{ secrets.STAGING_AUTH0_CLIENT_SECRET }}
                  elif [ "$BRANCH_NAME" == "dev" ]; then
                      AUTH0_SECRET=${{ secrets.DEV_AUTH0_CLIENT_SECRET }}
                  else
                      AUTH0_SECRET=null
                  fi
                  echo "::set-output name=auth0_secret::$AUTH0_SECRET"

            - name: Download files from the current repository
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install the auth0-deploy-cli
              run: npm install -g auth0-deploy-cli
            - name: Build Auth0 hooks
              run: npm run-script build
            - name: Import changes to the Auth0 staging account
              env:
                  AUTH0_CLIENT_SECRET: ${{ steps.set-client-secret.outputs.auth0_secret }}
              run: npm run deploy:${{ steps.extract_branch.outputs.branch }}
