# workflows/dockerfiles-check-pr.yml
#
# Dockerfiles: Check PR
# Check PRs that touch Dockerfiles for Dockerfile linting with Hadolint.
# Note: This does not consider mandelboxes; for those see mandelboxes-check-pr.yml.
#       Instead, this lints our miscellaneous Dockerfiles for development, config, and deployment.

name: "Dockerfiles: Check PR"

on:
  pull_request:
    paths:
      - "**/*Dockerfile"
      - ".github/workflows/dockerfiles-check-pr.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Linting
  # Checks for formatting and Dockerfile standards using Hadolint.
  dockerfiles-lint-dockerfiles:
    name: Linting
    runs-on: ubuntu-20.04
    container: hadolint/hadolint:v2.8.0-debian # This version should be updated periodically to use latest Hadolint rules

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      # Start from top-level folder to use .hadolint.yaml config
      - name: Check if Development Dockerfiles Follow Hadolint Standards
        run: hadolint ./**/*Dockerfile
