# workflows/ecs-host-service-check-pr.yml
#
# ECS Host Service: Check PR
# Checks an ECS Host Service PR for linting and building success.

name: "ECS Host Service: Check PR"

on:
  pull_request:
    paths:
      - "ecs-host-service/**"
      - "!ecs-host-service/README.md"
      - ".github/workflows/ecs-host-service-check-pr.yml"
  workflow_dispatch:

jobs:
  # Building
  # Check that the ECS Host Service builds.
  ecs-host-service-check-pr-building:
    name: Building
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Authenticate Go commands with GitHub
        env:
          GH_USERNAME: ${{ secrets.GHA_USERNAME }}
          GH_PAT: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
        run: git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/

      # Check go project (build, vet, format, lint)
      - name: Check Go project
        working-directory: ecs-host-service
        env:
          WEBSERVER_AUTH_SECRET_DEV: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_DEV }}
          WEBSERVER_AUTH_SECRET_STAGING: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING }}
          WEBSERVER_AUTH_SECRET_PROD: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD }}
          LOGZIO_SHIPPING_TOKEN: ${{ secrets.HOST_SERVICE_LOGZIO_SHIPPING_TOKEN }}
        run: |
          PATH=$PATH:~/go/bin
          # This will fail if unformatted
          make check
          # Show format-induced diff in GitHub Actions logs
          git diff HEAD --
          # This will return an error if there is a non-empty diff
          git diff-index --quiet HEAD --
