# workflows/ecs-host-service-check-pr.yml
#
# ECS Host Service: Check PR
# Checks an ECS Host Service PR for linting and building success.

name: "ECS Host Service: Check PR"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
            - project/**
        paths:
            - "ecs-host-service/**"
            - "!ecs-host-service/README.md"
            - ".github/workflows/ecs-host-service-check-pr.yml"
    workflow_dispatch:

jobs:
    # Building
    # Check that the ECS Host Service builds.
    ecs-host-service-check-pr-building:
        name: Building
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Setup Go environment
              uses: actions/setup-go@v2.1.3

            - name: Authenticate Go commands with GitHub
              run: |
                  git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/
              env:
                  GH_USERNAME: ${{ secrets.GHA_USERNAME }}
                  GH_PAT: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}

            # Install dependencies for `make format` and `make lint`
            # We make sure not to use `ecs-host-service` as the working directory to avoid polluting `go.mod` and `go.sum`
            - name: Install goimports
              run: |
                  go get -u golang.org/x/tools/cmd/goimports
                  go get -u golang.org/x/lint/golint

            # Build go project
            - name: Build Go project
              env:
                  WEBSERVER_AUTH_SECRET_DEV: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_DEV }}
                  WEBSERVER_AUTH_SECRET_STAGING: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING }}
                  WEBSERVER_AUTH_SECRET_PROD: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD }}
              working-directory: ecs-host-service
              run: make build

            # Check code formatting
            - name: Check if Code is Formatted with goimports
              working-directory: ecs-host-service
              run: |
                  PATH=$PATH:~/go/bin
                  # Apply goimports format changes to the current directory
                  make format
                  # Show diff in GitHub Actions logs
                  git diff HEAD --
                  # This will return an error if there is a non-empty diff
                  git diff-index --quiet HEAD --

            - name: Check Code with govet
              working-directory: ecs-host-service
              run: |
                  PATH=$PATH:~/go/bin
                  make vet

            - name: Check Code with golint
              working-directory: ecs-host-service
              run: |
                  PATH=$PATH:~/go/bin
                  make lint
