# workflows/ecs-host-service-check-pr.yml
#
# ECS Host Service: Check PR
# Checks an ECS Host Service PR for linting and building success.

name: "ECS Host Service: Check PR"

on:
    pull_request:
        paths:
            - "ecs-host-service/**"
            - "!ecs-host-service/README.md"
            - "main-webserver/db_migration/schema.sql"
            - ".github/workflows/ecs-host-service-check-pr.yml"
    workflow_dispatch:

jobs:
    # Building
    # Check that the ECS Host Service builds.
    ecs-host-service-check-pr-building:
        name: Building
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Setup Go environment
              uses: actions/setup-go@v2.1.3
              with:
                  go-version: "1.16"

            - name: Authenticate Go commands with GitHub
              env:
                  GH_USERNAME: ${{ secrets.GHA_USERNAME }}
                  GH_PAT: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
              run: git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/

            # Check go project (build, vet, format, lint)
            - name: Check Go project
              working-directory: ecs-host-service
              env:
                  HEROKU_USER: ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
                  HEROKU_APIKEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
                  LOGZIO_SHIPPING_TOKEN: ${{ secrets.HOST_SERVICE_LOGZIO_SHIPPING_TOKEN }}
              run: |
                  # Add Go to path
                  PATH=$PATH:~/go/bin

                  # This checks for building, vet, format and lint, and will fail if unformatted
                  make check

                  # Show format-induced diff in GitHub Actions logs
                  printf "\n\n\n =============="
                  git diff HEAD --
                  printf "\n\n\n =============="

                  # This will return an error if there is a non-empty diff
                  git diff-index --quiet HEAD --
