# workflows/ecs-host-service-linting.yml
#
# ECS Host Service: Linting
# Lint ECS Host Service using Goimports.

name: "ECS Host Service: Linting"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
            - project/**
        paths:
            - "ecs-host-service/**"
            - "!ecs-host-service/README.md"

jobs:
    ecs-host-service-linting-main:
        name: Lint ECS Host Service
        runs-on: ubuntu-20.04

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Setup Go environment
              uses: actions/setup-go@v2.1.3

            - name: Install goimports
              run: |
                  go get -u golang.org/x/tools/cmd/goimports

            - name: Check if code is linted with goimports
              run: |
                  PATH=$PATH:~/go/bin
                  result=$(goimports -l *.go fractallogger/*.go fractalwebserver/*.go) # goimports -l returns nothing if all files are formatted, else returns files that need formatting
                  if [ "$result" -ne "0" ]; then
                    (echo "To pass this check please lint the code with goimports" && false)
                  else
                    (echo "Code is linted with goimports" && true)
                  fi
