# workflows/main-webserver-analyze-datadog-events.yml
#
# Main Webserver: Analyze Datadog Events
# Runs daily, running analysis on Datadog events from the past day.

name: "Main Webserver: Analyze Datadog Events"

on:
    schedule:
        - cron: "0 0 * * 0" # weekly, on Sunday at 00:00
    workflow_dispatch:

jobs:
    main-webserer-analyze-datadog-events-main:
        name: Run Events Analysis
        runs-on: ubuntu-20.04

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
                  architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

            - name: Install dotenv, numpy, and datadog, boto3
              run: |
                  python -m pip install --upgrade pip
                  pip install python-dotenv numpy datadog boto3

            - name: Run Webserver Events Analysis Python Script
              run: python webserver/analytics/datadog/analyze.py weekly

            - name: Notify Slack
              run: |
                  curl -X POST \
                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"Webserver Weekly Events Analysis performed and visualized in Datadog.\", \"icon_emoji\": \":fractal:\"}" \
                  ${{ secrets.SLACK_HOOKS_ENDPOINT }}
