# workflows/main-webserver-clear-protocol-logs.yml
#
# Main Webserver: Clear Protocol Logs
# Runs monthly, emptying the S3 bucket which stores the protocol client/server logs.

name: "Main Webserver: Clear Protocol Logs"

on:
  schedule:
    - cron: "0 0 1 * *" # every month

jobs:
  main-webserver-clear-protocol-logs-main:
    name: Empty Protocol Logs from S3 Bucket
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Empty S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: fractal-protocol-logs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
