# workflows/mandelboxes-check-pr.yml
#
# Mandelboxes: Check PR
# Check a mandelboxes/protocol PR for Dockerfile linting and Docker images building success.

name: "Mandelboxes: Check PR"

on:
  pull_request:
    paths:
      - "mandelboxes/**"
      - "!mandelboxes/README.md"
      - ".github/workflows/mandelboxes-check-pr.yml"
      - "!mandelboxes/helper_scripts/run_mandelbox_image.sh"
      - "!mandelboxes/run_local_mandelbox_image.sh"
      - "!mandelboxes/run_remote_mandelbox_image.sh"
      - pyproject.toml
      - pylintrc
  workflow_dispatch:

jobs:
  # Linting
  # Checks for formatting and Dockerfile standards using Hadolint.
  mandelboxes-lint-dockerfiles:
    name: Linting
    runs-on: ubuntu-20.04
    container: hadolint/hadolint:v1.23.0 # This version should be updated periodically to use latest Hadolint rules

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      # Start from top-level folder to use .hadolint.yaml config
      - name: Check if Development Dockerfiles Follow Hadolint Standards
        run: hadolint ./**/*Dockerfile

      # Start from top-level folder to use .hadolint.yaml config
      - name: Check if Mandelbox Dockerfiles Follow Hadolint Standards
        run: |
          hadolint ./mandelboxes/*/Dockerfile.20
          hadolint ./mandelboxes/*/*/Dockerfile.20

  # Linting/formatting Python code in mandelboxes
  mandelboxes-python-scripts-linting:
    name: Lint mandelboxes Python Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9.10
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.9.10"

      - name: Install requirements
        working-directory: mandelboxes
        run: pip install -r helper_scripts/requirements.txt -r testing_scripts/requirements.txt

      - name: Add pylint-wrapper to the PATH
        run: echo "$GITHUB_WORKSPACE/.github/workflows/helpers" >> "$GITHUB_PATH"

      - name: Check if Code Matches Pylint Standards
        run: pylint-wrapper mandelboxes/helper_scripts mandelboxes/testing_scripts

  # Docker images building
  # Checks that the Docker images build successfully.
  mandelboxes-build-images:
    name: Building
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI # To get and install GRID driver
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Mandelboxes
        working-directory: mandelboxes
        run: ./build_mandelbox_image.sh --all
