# workflows/markdown-linting.yml
#
# Markdown: Linting
# Lint Markdown files using Prettier.

name: "READMEs: Linting"

on:
  pull_request:
    paths:
      - "**.md"
      - "**/**.md"
      - ".github/**/**.md"
      - ".github/workflows/markdown-linting.yml"
  workflow_dispatch:

jobs:
  readmes-linting-main:
    name: Lint Markdown Files (READMEs, etc.)
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      # We have to use npm install -g here, as the yarn
      # equivalent "yarn global add" doesn't correctly
      # add the command to the path in GitHub Actions.
      - name: Install Prettier
        run: npm install -g prettier

      - name: Check if Markdown files are Formatted
        run: |
          # We need to use globstar for glob expansion on bash
          shopt -s globstar
          prettier --check '**/**.md' # Prettier glob syntax hits all READMEs with this
          shopt -u globstar
