name: "Delete old artifacts"
on:
<<<<<<< HEAD
    schedule:
        - cron: "0 1 * * *" # every day

jobs:
    delete-artifacts:
        runs-on: ubuntu-latest
        steps:
            - uses: kolpav/purge-artifacts-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  expire-in: 7days # Setting this to 0 will delete all artifacts

=======
  schedule:
    - cron: "0 1 * * *" # every day

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7days # Setting this to 0 will delete all artifacts
>>>>>>> dev
