# workflows/meta-label-pull-requests.yml
#
# Meta: Label Pull Requests
# Labels pull requests with the subprojects they touch.

name: "Meta: Label Pull Requests"

on: pull_request

jobs:
  meta-label-pull-requests-main:
    name: Label Pull Request
    runs-on: ubuntu-20.04

    env:
      PR_LABEL_PREFIX: "📁 Repo:"

    steps:
      - name: Label Pull Request (.github, backend, and frontend subprojects)
        uses: adamzolyak/monorepo-pr-labeler-action@3.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: ".github|frontend|backend"
        with:
          prefix: ${{ env.PR_LABEL_PREFIX }}
      - name: Label Pull Request (monorepo root)
        uses: adamzolyak/monorepo-pr-labeler-action@3.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Match how we've been labeling our PRs before the action 3.0.0 changed
          # its default behavior to remove the prefix.
          prefix: ${{ env.PR_LABEL_PREFIX }}
