# workflows/meta-clear-releases.yml
#
# Meta: Clean Up Releases & Tags
# Runs weekly, deleting old releases and tags from github, keeping only the last 5.

name: "Meta: Clean Up Releases & Tags"

on:
    schedule:
        - cron: "0 0 * * 0" # every 7 days

jobs:
    meta-clear-releases-main:
        name: "Delete Old Releases & Tags"
        runs-on: ubuntu-20.04

        steps:
            - name: Purge releases/tags over 7 days old, keeping the 5 latest
              uses: dev-drprasad/delete-older-releases@v0.1.0
              with:
                  keep_latest: 5
                  delete_tags: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
