# workflows/microservices-check-pr.yml
#
# Microservices: Check PR
# Check a microservices PR to ensure that our service authentication and configuration is valid.

name: "Microservices: Check PR"

on:
    pull_request:
        paths:
            - "microservices/**"
            - "!microservices/README.md"
            - "!microservices/**/README.md"
            - ".github/workflows/microservices-check-pr.yml"
            - ".github/actions/generate-auth0-token"
            - ".github/actions/set-environment/action.yml"
    workflow_dispatch:

jobs:
    # Check that our Fractal Authentication API authentication is valid for all our environments dev/staging/prod
    microservices-auth0-verify-fractal-api-auth:
        name: "Auth0: Verify Fractal API Authentication for ${{ matrix.environment.name }}"
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                environment:
                    - name: Dev
                      ref: /refs/heads/dev
                    - name: Staging
                      ref: /refs/heads/staging
                    - name: Prod
                      ref: /refs/heads/prod

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

              # We are testing this configuration against deployable branches dev/staging/prod only
            - name: Set Workflow Environment
              id: set-workflow-environment
              uses: ./.github/actions/set-environment
              with:
                  ref: ${{ matrix.environment.ref }}

            - name: Obtain an Auth0 Access Token with Fractal API Audience
              id: get-token
              uses: ./.github/actions/generate-auth0-token
              with:
                  domain: ${{ steps.set-workflow-environment.outputs.auth0-domain }}
                  client-id: ${{ steps.set-workflow-environment.outputs.auth0-client-id }}
                  client-secret: ${{ secrets[steps.set-workflow-environment.outputs.auth0-client-secret-key] }}

    # Check that our Auth0 deployment setup works by attempting to retrieve the current upstream schema
    microservices-auth0-verify-tenant-schema-retrieval:
        name: "Auth0: Verify Tenant Schema Retrieval for ${{ matrix.environment.name }}"
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                environment:
                    - name: Dev
                      ref: /refs/heads/dev
                      branch: dev
                    - name: Staging
                      ref: /refs/heads/staging
                      branch: staging
                    - name: Prod
                      ref: /refs/heads/prod
                      branch: prod

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

              # We are testing this configuration against deployable branches dev/staging/prod only
            - name: Set Workflow Environment
              id: set-workflow-environment
              uses: ./.github/actions/set-environment
              with:
                  ref: ${{ matrix.environment.ref }}

            - name: Install Node.js 15
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: 15

            - name: Install Dependencies
              working-directory: microservices/auth0
              run: yarn install

            - name: Dump the Upstream Auth0 Tenant
              working-directory: microservices/auth0
              env:
                  AUTH0_CLIENT_SECRET: ${{ secrets[format('AUTH0_GHA_CLIENT_SECRET_{0}', matrix.environment.branch)] }}
                  GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
                  APPLE_OAUTH_SECRET: ${{ secrets.APPLE_OAUTH_SECRET }}
              run: yarn run dump:${{ matrix.environment.branch }}
