# workflows/microservices-check-pr.yml
#
# Microservices: Check PR
# Check a microservices PR to ensure that our service authentication and configuration is valid.

name: "Microservices: Check PR"

on:
    pull_request:
        paths:
            - "microservices/**"
            - "!microservices/README.md"
            - "!microservices/**/README.md"
            - ".github/workflows/microservices-check-pr.yml"
            - ".github/actions/generate-auth0-token"
            - ".github/actions/set-environment/action.yml"
    workflow_dispatch:

jobs:
    # Check that our Auth0 management API authentication is valid for all our environments dev/staging/prod
    microservices-auth0-verify-management-auth:
        name: "Auth0: Verify Management Authentication for ${{ matrix.environment.name }}"
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                environment:
                    - name: Dev
                      ref: /refs/heads/dev
                    - name: Staging
                      ref: /refs/heads/staging
                    - name: Prod
                      ref: /refs/heads/prod
        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2
            - name: Set Workflow Environment
              id: set-workflow-environment
              uses: ./.github/actions/set-environment
              with:
                  # We are testing this configuration against deployable branches dev/staging/prod only
                  ref: ${{ matrix.environment.ref }}
                  deploy: true
            - name: Obtain a Fractal access token
              id: get-token
              uses: ./.github/actions/generate-auth0-token
              with:
                  domain: ${{ steps.set-workflow-environment.outputs.auth0-domain }}
                  client-id: ${{ steps.set-workflow-environment.outputs.auth0-client-id }}
                  client-secret: ${{ secrets[steps.set-workflow-environment.outputs.auth0-client-secret-key] }}
