# Run streaming tests between Azure (server) and GitHub VMs (client) every night

name: Nightly testing
# Run every day at 6 am UTC, 2am eastern
on:
    schedule:
        - cron: "0 6 * * *"

jobs:
    trigger-testing:
        runs-on: ubuntu-latest
        steps:
            # TODO switch this to GITHUB_TOKEN once workflow_dispatch supports GHA initiated dispatches
            # (currently it requires the dispatcher to be a user, so a personal access token must be used
            # here)

            # The workflow ID can be determined by running:
            # ```
            # curl -u "$TOKEN:" \
            #   -H "Accept: application/vnd.github.v3+json" \
            #   https://api.github.com/repos/fractal/protocol/actions/workflows
            # ```

            # NOTE: the root "ref" tag points to `master` because that is the version of the workflow that
            # we want to run (as in, that is the branch containing the specific YAML file that should be used)

            # Pipe secrets.GHA_PERSONAL_ACCESS_TOKEN to base64 so that the user can see it in the logs
            # since GHA auto redacts secrets.
            - run: |
                  echo "base64 encoded GHA_PERSONAL_ACCESS_TOKEN (pipe to `base64 -d` to decode): "
                  echo "${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}" | base64
                  curl -u "${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}:" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/fractal/protocol/actions/workflows/${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}/dispatches \
                    -d '{"ref": "master", "inputs": {"ref": "dev", "should_test": "true", "should_release": "false"}}'
