# Deploy Docker images to AWS ECR
name: Push images

# Publish on update to master branch
on:
    push:
        branches: [eric/script-automate]
    workflow_dispatch:

jobs:
    build-desktop-app:
        name: Build-desktop-app
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
                  submodules: recursive
            
            - name: Build protocol
              run: cd protocol && ./build-protocol.sh release
            
            - name: Publish the client-application
              run: ./publish-version.sh release
            # - name: Build release protocol
            #   run: ./build_protocol.sh release

            # - name: Build container images
            #   run: |
            #       for app in ${{ env.apps }}
            #       do
            #         ./build_container_image.sh $app
            #       done

            # - name: Notify Slack
            #   run: |
            #       curl -X POST \
            #       --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"Container images builds pushed to production via Docker push to ECR.\", \"icon_emoji\": \":fractal:\"}" \
            #       https://hooks.slack.com/services/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

