# Deploy Docker images to AWS ECR
name: Push images

# Publish on update to master branch
# https://github.com/samuelmeuli/action-electron-builder for macOS building
on:
    push:
        branches: [eric/add-wf]
    workflow_dispatch:

env:
    CMAKE_VERSION: 3.16.4
    NINJA_VERSION: 1.9.0
    BUILD_TYPE: Debug
    CCACHE_VERSION: 3.7.7

jobs:
    build-desktop-app:
        name: Build-desktop-app
        runs-on: macos-10.14

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
                  submodules: recursive

            - name: Publish the client-application
              run: cd client-applications && cd desktop && ./publish.sh release

