# workflows/python-linting.yml
#
# Python: Linting
# Check Python formatting by running Black on the entire monorepo.

name: "Python: Linting"

on:
  pull_request:
    paths:
      - "**.py"
      - .github/workflows/python-linting.yml
      - pyproject.toml
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: python-linting-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  python-linting:
    name: Check Python Formatting
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v3.1.1
        with:
          python-version: "3.10.4"

      - name: Install Black
        run: pip install $(grep -i ^black .github/workflows/helpers/requirements.txt)

      - name: Check Python formatting with Black
        run: black --check .
