# workflows/readmes-linting.yml
#
# READMEs: Linting
# Lint READMEs using Prettier.

name: "READMEs: Linting"

on:
    pull_request:
        paths:
            - "README.md"
            - "**/README.md"
            - ".github/**/README.md"
            - ".github/workflows/readmes-linting.yml"
    workflow_dispatch:

jobs:
    readmes-linting-main:
        name: Lint READMEs
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 15
              uses: actions/setup-node@v2.3.0
              with:
                  node-version: "15"

            # We have to use npm install -g here, as the yarn
            # equivalent "yarn global add" doesn't correctly
            # add the command to the path in GitHub Actions.
            - name: Install Prettier
              run: npm install -g prettier

            - name: Check if READMEs are Formatted
              run: prettier --check '**/README.md' # Prettier glob syntax hits all READMEs with this
