# workflows/readmes-linting.yml
#
# READMEs: Linting
# Lint READMEs using Prettier.

name: "READMEs: Linting"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
        paths:
            - "README.md"
            - "**/README.md"
            - ".github/workflows/README.md"
            - ".github/workflows/readmes-linting.yml"
    workflow_dispatch:

jobs:
    readmes-linting-main:
        name: Lint READMEs
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install Prettier
              run: npm install -g prettier

            - name: Check if READMEs are Formatted
              run: prettier --check '**/README.md' # Prettier glob syntax hits all READMEs with this
