# workflows/readmes-linting.yml
#
# READMEs: Linting
# Lint READMEs using Prettier.

name: "READMEs: Linting"

on:
  pull_request:
    paths:
      - "README.md"
      - "**/README.md"
      - ".github/**/README.md"
      - ".github/workflows/readmes-linting.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: readmes-linting-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  readmes-linting-main:
    name: Lint READMEs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      # We have to use npm install -g here, as the yarn
      # equivalent "yarn global add" doesn't correctly
      # add the command to the path in GitHub Actions.
      - name: Install Prettier
        run: npm install -g prettier

      - name: Check if READMEs are Formatted
        run: prettier --check '**/README.md' # Prettier glob syntax hits all READMEs with this
