# workflows/shell-scripts-linting-and-checking.yml
#
# Shell Scripts: Linting and Checking
# Lint and enforce good practices for shell scripts.

name: "Shell Scripts: Linting and Checking"

on:
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/shell-scripts-linting-and-checking.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: shell-scripts-linting-and-checking-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shell-scripts-linting-main:
    name: Lint Shell Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10.0
        uses: actions/setup-python@v3.1.0
        with:
          python-version: "3.10.0"

      - name: Install beautysh
        working-directory: mandelboxes/scripts
        run: pip install -r requirements.txt

      - name: Run Beautysh to Check Scripts Formatting
        run: |
          # We need to use globstar for glob expansion on bash
          shopt -s globstar
          beautysh **/*.sh --indent-size 2 --check
          shopt -u globstar

      - name: Check that All Bash Scripts Start with "#!/bin/bash"
        run: .github/workflows/helpers/shell-scripts/check-shebang.sh

      - name: Check that All Bash Scripts Contain "set -Eeuo pipefail"
        run: .github/workflows/helpers/shell-scripts/check-pipefail.sh

  shell-scripts-shellcheck:
    name: Run ShellCheck on Shell Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      # Disabled the following codes in some files because fixing the scripts according to the Shellcheck wishes was either causing crashes or it was too cumbersome:
      # * SC2028: echo won't expand escape sequences. Consider printf
      # * SC2046: Quote this to prevent word splitting.
      # * SC2086: Double quote to prevent globbing and word splitting.
      # * SC2154: var is referenced but not assigned.
      # * SC1004: This backslash+linefeed is literal. Break outside single quotes if you just want to break the line.
      - name: Run ShellCheck on all folders
        run: |
          python3 .github/workflows/helpers/shell-scripts/check-shellcheck.py \
            --exclude-dirs="frontend/client-applications/node_modules/" \
            --exclude-codes="backend/webserver/ephemeral_db_setup/fetch_db.sh:SC2028 \
            protocol/build_protocol_targets.sh:SC2046,SC2086 protocol/lint-cmake.sh:SC2086 \
            mandelboxes/base/display/whist-display.sh:SC2154 mandelboxes/base/utils/run-as-whist-user.sh:SC1004 \
            mandelboxes/development/client/run-whist-client.sh:SC2086 mandelboxes/base/main/run-whist-server.sh:SC2086,SC2046"
