# workflows/shell-scripts-linting.yml
#
# Shell Scripts: Linting
# Lint and enforce good practices for shell scripts.

name: "Shell Scripts: Linting"

on:
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/shell-scripts-linting.yml"
  workflow_dispatch:

jobs:
  shell-scripts-linting-main:
    name: Lint Shell Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.0
        uses: actions/setup-python@v2.3.0
        with:
          python-version: "3.10.0"

      - name: Install beautysh
        working-directory: mandelboxes/helper_scripts
        run: pip install -r requirements.txt

      - name: Run Beautysh to Check Scripts Formatting
        run: |
          # We need to use globstar for glob expansion on bash
          shopt -s globstar
          beautysh **/*.sh --indent-size 2 --check
          shopt -u globstar

      - name: Check that All Bash Scripts Start with "#!/bin/bash"
        run: .github/workflows/helpers/shell-scripts/check-shebang.sh

      - name: Check that All Bash Scripts Contain "set -Eeuo pipefail"
        run: .github/workflows/helpers/shell-scripts/check-pipefail.sh

  shell-scripts-shellcheck:
    name: Run ShellCheck on Shell Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Run ShellCheck on frontend folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./frontend"
          ignore_paths: "./frontend/client-applications/node_modules/"

      - name: Run ShellCheck on backend folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./backend/"

      - name: Run ShellCheck on protocol folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./protocol/"

      - name: Run ShellCheck on .github folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./.github/"

      - name: Run ShellCheck on host-setup folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./host-setup/"

      - name: Run ShellCheck on mandelboxes folder
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./mandelboxes/"
