name: "Main Webserver: Resource Cleanup"

on:
    push:
        branches:
            - mia/kill-packer-instances

jobs:
    temp:
        name: "Temp"
        runs-on: ubuntu-20.04
        steps:
            - name: "temp"
              run: |
                  echo "hey there"
                  echo false

    kill-packer-instances:
        name: "Kill Packer Instances if Workflow Failed"
        needs: temp
        if: always()
        runs-on: ubuntu-20.04
        steps:
            - name: Configure Python
              uses: actions/setup-python@v1

            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_EC2_S3_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_EC2_S3_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Kill All Packer Instances
              run: |
                  pip install aws-hashicorp-packer-reaper
                  aws-hashicorp-packer-reaper list
                  aws-hashicorp-packer-reaper terminate --older-than 1s
