name: "Main Webserver: Resource Cleanup"

on:
    push:
        branches:
            - mia/kill-packer-instances

jobs:
    kill-packer-instances:
        name: "Kill Packer Instances if Workflow Failed"
        if: always()
        runs-on: ubuntu-20.04
        steps:
            - name: Configure AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_EC2_S3_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_EC2_S3_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.aws_new_ami_source_region }}
            - name: Kill All Packer Instances
              uses: actions/setup-python@v1
                  pip install aws-hashicorp-packer-reaper
                  aws-hashicorp-packer-reaper list
                  aws-hashicorp-packer-reaper terminate --older-than 1s
