# workflows/main-webserver-check-pr.yml

name: "Test Tag Creation"

on:
    pull_request:
        branches:
            - dev
    workflow_dispatch:

jobs:
    test-tag-creation:
        name: Test Tag Creation
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Retrieve Today's Date
              run: echo "date=$(date)" >> $GITHUB_ENV

            - name: Create GitHub Tag
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ github.ref }}
                draft: false
                body: Fractal Promotion to Production for Version [TODO] on ${{ env.date }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



