# workflows/main-webserver-check-pr.yml

name: "Test Tag Creation"

on:
    pull_request:
        branches:
            - dev
    workflow_dispatch:

jobs:
    test-tag-creation:
        name: Test Tag Creation
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Create GitHub Tag
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



