name: "Database Migration Push"

on:
    push:
        branches:
            - mia/fctl-395-make-db-migration-slack-notif-go-to

jobs:
    run-migra-diff:
        name: Run Migra Diff
        runs-on: ubuntu-20.04

        env:
            SLACK_CHANNEL: "alerts-${GITHUB_REF##*/}"

        steps:
            - name: Notify Slack
              if: success()
              shell: python3 {0}
              run: |
                  import os
                  print(os.environ["SLACK_CHANNEL"])
