# workflows/core-ts-linting.yml
#
# Core TypeScript Library: Check PR
# Checks a Core-TS PR for linting and testing success.

name: "Test"

on:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Test
              run: echo "${GITHUB_REF#refs/heads/}"
