# workflows/webserver-empty-protocol-logs-s3-bucket.yml
#
# Webserver: Empty Protocol Logs S3 Bucket
# Periodically empty the S3 bucket which stores the Fractal protocol logs.

name: "Webserver: Empty Protocol Logs S3 Bucket"

on:
  schedule:
    - cron: "0 0 1 * *" # once every month

jobs:
  empty-s3-bucket:
    name: Empty S3 Bucket
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

      - name: Empty S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: fractal-protocol-logs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Notify Slack
        run: |
          curl -X POST \
          --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"S3 Bucket fractal-protocol-logs Monthly Emptying Completed by GitHub Actions.\", \"icon_emoji\": \":fractal:\"}" \
          https://hooks.slack.com/services/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
