# workflows/whist-build-and-publish-documentation.yml
#
# Whist: Build & Publish Documentation
# Build and conditionally deploy fractal/whist monorepo documentation. Although this
# workflow is triggered by both pull requests and pushes, the steps that deploy
# the built documentation only run when the triggering event is a push.

name: "Whist: Build & Publish Documentation"

on:
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/whist-build-and-publish-documentation.yml"
      - "host-service/**"
      - "protocol/**"
      - "webserver/**"
  push:
    branches:
      - dev
    paths:
      - ".github/workflows/whist-build-and-publish-documentation.yml"
      - "host-service/**"
      - "protocol/**"
      - "webserver/**"
  workflow_dispatch:

jobs:
  whist-build-and-publish-documentation:
    name: Build & Publish Whist Internal Documentation to fractal/docs
    runs-on: ubuntu-20.04
    concurrency: whist-build-and-publish-documentation
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      ################################# CONFIG STEPS ###############################

      - name: Checkout the fractal/fractal Git Repository
        uses: actions/checkout@v2
        with:
          path: fractal

      - name: Checkout the fractal/docs Git Repository
        uses: actions/checkout@v2
        with:
          repository: fractal/docs
          token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
          path: docs

      - name: Setup Python-based notifications
        working-directory: fractal/.github/workflows/helpers
        run: ./notifications/setup_notifications.sh

      ##############################################################################
      ############################## HOST-SERVICE STEPS ############################

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.17"

      - name: Build Host Service Documentation
        working-directory: fractal/host-service
        run: make docs

      - name: Diff Old and New Documentation
        id: host-service-diff
        run: |
          git diff --no-index fractal/host-service/build/docs docs/host-service && echo "No changes detected"
          echo "::set-output name=changed::$?"

      - name: Copy New Host-Service Documentation into the fractal/docs Working Tree (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && steps.host-service-diff.outputs.changed == true }}
        run: rm -rf docs/host-service && cp -r fractal/host-service/build/docs docs/host-service

      ##############################################################################
      ################################ PROTOCOL STEPS ##############################

      # Necessary for downloading protocol libs and base Dockerfile Nvidia GRID drivers from AWS S3
      - name: Configure AWS S3 CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Protocol Documentation
        working-directory: fractal/protocol
        run: ./build_protocol_targets.sh docs

      - name: Diff Old and New Documentation
        id: protocol-diff
        run: |
          # Since the protocol is built inside a docker container, the folder is build-docker
          git diff --no-index fractal/protocol/build-docker/docs/html docs/protocol && echo "No changes detected"
          echo "::set-output name=changed::$?"

      - name: Copy New Protocol Documentation into the fractal/docs Working Tree (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && steps.protocol-diff.outputs.changed == true }}
        run: rm -r docs/protocol && cp -r fractal/protocol/build-docker/docs/html docs/protocol # Since the protocol is built inside a Docker container, the folder is build-docker

      ##############################################################################
      ################################ WEBSERVER STEPS #############################

      # Install the version of Sphinx specified in webserver/requirements-test.txt
      - name: Install requirements
        run: |
          pip install $(cat fractal/webserver/requirements.txt)
          pip install $(cat fractal/webserver/requirements-test.txt)

      - name: Build the Latest Documentation
        working-directory: fractal/webserver/docs
        run: sphinx-apidoc --no-toc -fo . ../app && make html

      - name: Diff Old and New Documentation
        id: webserver-diff
        run: |
          git diff --no-index fractal/webserver/docs/_build/html docs/webserver && echo "No changes detected"
          echo "::set-output name=changed::$?"

      - name: Copy New Webserver Documentation into the fractal/docs Working Tree (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && steps.webserver-diff.outputs.changed == true }}
        run: rm -r docs/webserver && cp -r fractal/webserver/docs/_build/html docs/webserver

      ##############################################################################
      ################################# PUBLISH STEPS ##############################

      - name: Commit the Documentation Changes to fractal/docs (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (steps.host-service-diff.outputs.changed == true || steps.protocol-diff.outputs.changed == true || steps.webserver-diff.outputs.changed == true) }}
        working-directory: docs
        run: |
          # Set the author of the commit in fractal/docs to be the user
          # who just pushed to the dev branch of the monorepo.
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"

          # Authenticate Git as Phil with GitHub
          git config credential.helper store
          git credential approve <<EOF
          protocol=https
          host=github.com
          username=phil@whist.com
          password=${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
          EOF

          # Stage, commit, and push documentation changes
          git add host-service
          git commit -F - <<EOF
          Update Whist internal documentation (https://github.com/fractal/fractal/commit/${{ github.sha }})
          EOF
          git show --stat
          git push

      ##############################################################################

      - name: Notify Slack on Workflow Error (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (steps.host-service-diff.outputs.changed == true || steps.protocol-diff.outputs.changed == true || steps.webserver-diff.outputs.changed == true) && failure() }}
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT_DEV }}"
          SLACK_CHANNEL = "#alerts-dev"
          BODY = "@releases :rotating_light: Failed to deploy Whist Internal Documentation to `docs.whist.com`, investigate immediately :rotating_light: (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY)

      - name: Notify Slack on Workflow Success (Only on Push/Workflow_dispatch Events)
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (steps.host-service-diff.outputs.changed == true || steps.protocol-diff.outputs.changed == true || steps.webserver-diff.outputs.changed == true) && success() }}
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT_DEV }}"
          SLACK_CHANNEL = "#alerts-dev"
          TITLE = ":orange_book: Whist Internal Documentation Deployed :orange_book:"
          BODY = "Whist Internal Documentation Deployed to `docs.whist.com` (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
