# workflows/whist-browser-build-and-deploy.yml
#
# Whist Browser: Build & Deploy
# Build and deploy the Whist Browser, bundling the Whist monorepo and the Brave Chromium browser for
# our dev environment, nightly.

name: "Whist Browser: Build & Deploy"

on:
  # On dev, we run a nightly build on weekdays (days of the week 1-5) at 00:01 UTC.
  schedule:
    - cron: "1 0 * * 1,2,3,4,5"
  # On staging & prod, we run a build for each promotion (push to branch).
  push:
  branches:
    - prod
    - staging
  paths-ignore:
    - "README.md"
    - "**/README.md"
    - ".github/workflows/README.md"
  workflow_dispatch:

jobs:
  # This job cross-compiles the Whist Browser to x86_64 from our NYC office M1 Mac Mini self-hosted runner.
  whist-browser-build-macos:
    name: "Nightly: macOS (${{ matrix.config.arch}})"
    runs-on: [self-hosted, macOS, ARM64]
    strategy:
      matrix:
        config:
          - arch: "x86_64"
          - arch: "arm64"
    env:
      x86_64-binary-tar-name: whist-browser-macos-x86_64.tar.gz
      arm64-binary-tar-name: whist-browser-macos-arm64.tar.gz
      x86_64-s3-bucket-uri: s3://whist-browser-macos-x86_64
      arm64-s3-bucket-uri: s3://whist-browser-macos-arm64
      s3-bucket-region: us-east-1
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          repository: whisthq/brave-browser
          ref: main
          fetch-depth: 1 # Only fetch the latest commit, since the history is so large
          token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}

      - name: Configure AWS S3 CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.s3-bucket-region }}

      # Building Brave/Chromium requires specific Node & npm versions, and Xcode. For full
      # details, see: https://github.com/whisthq/brave-browser#readme
      - name: Log NodeJS, npm and Xcode versions
        working-directory: brave-browser
        run: |
          echo "NodeJS & npm versions:\n"
          node --version
          npm --version

          echo "Verify that Xcode is installed and up-to-date:\n"
          xcode-select --install
          xcodebuild -version

      - name: Initialize the build environment
        working-directory: brave-browser
        run: npm install

      - name: Set target architecture
        working-directory: brave-browser
        run: npm config set target_arch "${{ matrix.config.arch }}"

      - name: Fetch Chromium source & dependencies
        working-directory: brave-browser
        run: npm run init

      - name: Build Whist Browser
        working-directory: brave-browser
        run: npm run build

      # TODO: configure the Chrome keys and other configs for creating a Release build
      # This may require some Google keys, so I (Phil) need to look into that
      - name: Build Whist Browser
        working-directory: brave-browser
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            npm run build Release
            echo "build_type=Release" >> $GITHUB_ENV
          else
            npm run build Debug
            echo "build_type=Debug" >> $GITHUB_ENV
          fi

      - name: Tar & Upload Whist Browser to AWS S3
        working-directory: brave-browser/src/out
        run: |
          tar -zcvf ${{ env.${{ matrix.config.arch }}-binary-tar-name }} "Component_${{ matrix.config.arch }}/Brave Browser ${{ env.build_type }}.app"
          aws s3 cp ${{ env.${{ matrix.config.arch }}-binary-tar-name }} ${{ env.${{ matrix.config.arch }}-s3-bucket-uri }}/${{ env.${{ matrix.config.arch }}-binary-tar-name }}

      ###################################################################################

      - name: Checkout whisthq/whist Git Repository
        uses: actions/checkout@v2

      - name: Setup Python-based notifications
        working-directory: .github/workflows/helpers
        run: ./notifications/setup_notifications.sh

      - name: Notify Slack on Workflow Error (Only on Push/Workflow_dispatch Events)
        if: failure()
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT_DEV }}"
          BODY = f"@releases :rotating_light: Failed to deploy Whist Browser (Nightly macOS) to AWS S3, investigate immediately :rotating_light: (<https://github.com/whisthq/whist/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, body=BODY)

      - name: Notify Slack on Success
        if: success()
        shell: python3 {0}
        run: |
          from notifications.slack_bot import slack_post
          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT_DEV }}"
          TITLE = ":brave: Whist Chromium Browser (Nightly macOS) Deployed :brave:"
          BODY = f"Whist Chromium Browser (Nightly macOS) deployed via upload to AWS S3 (<https://github.com/whisthq/whist/actions/runs/${{ github.run_id }} | see logs>)"
          slack_post(slack_webhook=SLACK_WEBHOOK, body=BODY, title=TITLE)
