# workflows/workflows-linting.yml
#
# Workflows: Linting
# Lint YAML workflows using Prettier.

name: "Workflows: Linting"

on:
    pull_request:
        paths:
            - ".github/workflows/**"
            - "!.github/workflows/README.md"
            - ".github/workflows/workflows-linting.yml"
    workflow_dispatch:

jobs:
    workflows-linting-main:
        name: Lint GitHub Actions Workflows
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 14
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14

            # We have to use npm install -g here, as the yarn
            # equivalent "yarn global add" doesn't correctly
            # add the command to the path in GitHub Actions.
            - name: Install Prettier
              run: npm install -g prettier

            - name: Check if Code is Formatted
              working-directory: .github/workflows
              run: prettier --check '*.yml'
